// lib/seedData/analytical/4-11-inphrared-spektroskpi-ir.ts
//
// অধ্যায় 4.11 — ইনফ্রারেড স্পেকট্রোস্কপি (IR) (Analytical Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter411: SeedChapter = {
  code: "4.11",
  category: "analytical-chemistry",
  structure: "3-level",
  chapterTitle: "ইনফ্রারেড স্পেকট্রোস্কপি (IR)",
  chapterOrder: 110,
  topics: [
    {
      title: "IR Spectroscopy এর মৌলিক ধারণা",
      slug: "ir-spectroscopy-er-moulik-dharna",
      summary: "",
      subtopics: [
        {
          title: "Electromagnetic spectrum এ IR region",
          slug: "electromagnetic-spectrum-e-ir-region",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Near IR, Mid IR, Far IR",
          slug: "near-ir-mid-ir-far-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Vibrational spectroscopy এর ধারণা",
          slug: "vibrational-spectroscopy-er-dharna",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular vibration",
          slug: "molecular-vibration",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bond stretching (IR)",
          slug: "bond-stretching-ir-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bond bending (IR)",
          slug: "bond-bending-ir-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Molecular Vibration",
      slug: "molecular-vibration-2",
      summary: "",
      subtopics: [
        {
          title: "Stretching vibration",
          slug: "stretching-vibration-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Symmetric stretching",
          slug: "symmetric-stretching",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Asymmetric stretching",
          slug: "asymmetric-stretching",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bending vibration (Molecular)",
          slug: "bending-vibration-molecular",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Scissoring",
          slug: "scissoring",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Rocking",
          slug: "rocking",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Wagging",
          slug: "wagging",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Twisting",
          slug: "twisting",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "IR Absorption Principle ও Instrumentation",
      slug: "ir-absorption-principle-o-instrumentation",
      summary: "",
      subtopics: [
        {
          title: "IR radiation absorption",
          slug: "ir-radiation-absorption",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Dipole moment পরিবর্তন",
          slug: "dipole-moment-pribrtn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Selection rule (IR)",
          slug: "selection-rule-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Vibrational frequency",
          slug: "vibrational-frequency",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "IR source",
          slug: "ir-source",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Monochromator (IR)",
          slug: "monochromator-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Interferometer",
          slug: "interferometer",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Detector (IR)",
          slug: "detector-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Sample holder",
          slug: "sample-holder",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "FTIR ও Spectrum Analysis",
      slug: "ftir-o-spectrum-analysis",
      summary: "",
      subtopics: [
        {
          title: "Fourier Transform principle",
          slug: "fourier-transform-principle",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "FTIR instrument design",
          slug: "ftir-instrument-design",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Advantages of FTIR",
          slug: "advantages-of-ftir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Spectrum interpretation (IR)",
          slug: "spectrum-interpretation-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Functional group identification (IR)",
          slug: "functional-group-identification-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fingerprint region",
          slug: "fingerprint-region-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Characteristic absorption peaks",
          slug: "characteristic-absorption-peaks",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Unknown compound identification",
          slug: "unknown-compound-identification",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Applications of IR",
      slug: "applications-of-ir",
      summary: "",
      subtopics: [
        {
          title: "Organic compound identification (IR)",
          slug: "organic-compound-identification-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pharmaceutical analysis (IR)",
          slug: "pharmaceutical-analysis-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Polymer analysis (IR)",
          slug: "polymer-analysis-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Environmental analysis (IR)",
          slug: "environmental-analysis-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Quality control (IR)",
          slug: "quality-control-ir",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter411;
