// lib/seedData/analytical/4-41-analytical-chemistry-laboratory-techniques.ts
//
// অধ্যায় 4.41 — Analytical Chemistry Laboratory Techniques (Analytical Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter441: SeedChapter = {
  code: "4.41",
  category: "analytical-chemistry",
  structure: "3-level",
  chapterTitle: "Analytical Chemistry Laboratory Techniques",
  chapterOrder: 410,
  topics: [
    {
      title: "Laboratory Safety",
      slug: "laboratory-safety",
      summary: "",
      subtopics: [
        {
          title: "Hazardous chemical handling",
          slug: "hazardous-chemical-handling",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Toxic substance management",
          slug: "toxic-substance-management",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Corrosive chemical safety",
          slug: "corrosive-chemical-safety",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Flammable chemical handling",
          slug: "flammable-chemical-handling",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chemical labeling",
          slug: "chemical-labeling",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glassware handling",
          slug: "glassware-handling",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Instrument safety (Lab)",
          slug: "instrument-safety-lab",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrical safety (Lab)",
          slug: "electrical-safety-lab",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "High temperature equipment safety",
          slug: "high-temperature-equipment-safety",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Personal protective equipment (PPE)",
          slug: "personal-protective-equipment-ppe",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Safety glasses",
          slug: "safety-glasses",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Gloves",
          slug: "gloves",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Laboratory coat",
          slug: "laboratory-coat",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Emergency procedures",
          slug: "emergency-procedures",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Laboratory Glassware and Equipment",
      slug: "laboratory-glassware-and-equipment",
      summary: "",
      subtopics: [
        {
          title: "Beaker",
          slug: "beaker",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Flask",
          slug: "flask",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pipette",
          slug: "pipette",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Burette",
          slug: "burette",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Measuring cylinder",
          slug: "measuring-cylinder",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Analytical balance",
          slug: "analytical-balance",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "pH meter (Equipment)",
          slug: "ph-meter-equipment",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Centrifuge",
          slug: "centrifuge",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Water bath",
          slug: "water-bath",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Oven (Lab Equipment)",
          slug: "oven-lab-equipment",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Muffle furnace",
          slug: "muffle-furnace",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Spectrophotometer",
          slug: "spectrophotometer",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chromatograph",
          slug: "chromatograph",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mass spectrometer (Lab Equipment)",
          slug: "mass-spectrometer-lab-equipment",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrochemical analyzer",
          slug: "electrochemical-analyzer",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter441;
