// lib/seedData/analytical/4-51-raman-spektroskpi.ts
//
// অধ্যায় 4.51 — রামান স্পেকট্রোস্কপি (Analytical Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter451: SeedChapter = {
  code: "4.51",
  category: "analytical-chemistry",
  structure: "3-level",
  chapterTitle: "রামান স্পেকট্রোস্কপি",
  chapterOrder: 510,
  topics: [
    {
      title: "Raman Spectroscopy এর মৌলিক ধারণা ও Theory",
      slug: "raman-spectroscopy-er-moulik-dharna-o-theory",
      summary: "",
      subtopics: [
        {
          title: "Raman effect",
          slug: "raman-effect-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Inelastic scattering",
          slug: "inelastic-scattering",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Rayleigh scattering",
          slug: "rayleigh-scattering",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Stokes scattering",
          slug: "stokes-scattering",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Anti-Stokes scattering",
          slug: "anti-stokes-scattering",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular polarizability",
          slug: "molecular-polarizability",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Vibrational energy levels",
          slug: "vibrational-energy-levels",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Raman active vibration",
          slug: "raman-active-vibration",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Selection rules (Raman)",
          slug: "selection-rules-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Raman Instrumentation",
      slug: "raman-instrumentation",
      summary: "",
      subtopics: [
        {
          title: "Laser source (Raman)",
          slug: "laser-source-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Monochromatic radiation",
          slug: "monochromatic-radiation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Filters",
          slug: "filters",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mirrors",
          slug: "mirrors",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Beam splitter",
          slug: "beam-splitter",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "CCD detector (Raman)",
          slug: "ccd-detector-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Photomultiplier detector",
          slug: "photomultiplier-detector",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Advanced Raman Techniques ও Applications",
      slug: "advanced-raman-techniques-o-applications",
      summary: "",
      subtopics: [
        {
          title: "FT-Raman spectroscopy",
          slug: "ft-raman-spectroscopy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Resonance Raman spectroscopy",
          slug: "resonance-raman-spectroscopy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Surface Enhanced Raman Spectroscopy (SERS)",
          slug: "surface-enhanced-raman-spectroscopy-sers-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pharmaceutical identification (Raman)",
          slug: "pharmaceutical-identification-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nanomaterial analysis (Raman)",
          slug: "nanomaterial-analysis-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biological analysis (Raman)",
          slug: "biological-analysis-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Art conservation",
          slug: "art-conservation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chemical imaging (Raman)",
          slug: "chemical-imaging-raman",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter451;
