// ─── Phase 1: Extended Element Data ────────────────────────────────────────
// এই ফাইলটি elementData.ts কে সম্পূর্ণ করে — atomicNumber দিয়ে lookup করে
// অতিরিক্ত প্রপার্টি (radii, ionization energy, isotopes, discovery details ইত্যাদি)।
// মূল elementData.ts অপরিবর্তিত থাকে; এই ফাইলটি আলাদাভাবে merge করা হয়।

export interface IonizationEnergies {
  first: number | null;   // kJ/mol
  second: number | null;
  third: number | null;
}

export interface Radii {
  atomic: number | null;     // pm (empirical/calculated)
  covalent: number | null;   // pm
  ionic: number | null;      // pm (most common ion, approximate)
  vanDerWaals: number | null; // pm
}

export interface IsotopeInfo {
  symbol: string;       // e.g. "C-14"
  type: "stable" | "radioactive";
  abundance?: string;    // e.g. "98.93%" — শুধু stable আইসোটোপের জন্য
  halfLife?: string;     // e.g. "5,730 বছর" — শুধু radioactive আইসোটোপের জন্য
}

export interface DiscoveryDetail {
  place: string;         // আবিষ্কারের স্থান/দেশ
  nameOrigin: string;    // নামের উৎস ব্যাখ্যা (বাংলা)
}

export interface ExtendedElementData {
  radii: Radii;
  ionizationEnergies: IonizationEnergies;
  electronAffinity: number | null;   // kJ/mol
  crystalStructure: string;
  hardnessMohs: number | null;
  heatOfFusion: number | null;       // kJ/mol
  heatOfVaporization: number | null; // kJ/mol
  molarVolume: number | null;        // cm³/mol
  notableIsotopes: IsotopeInfo[];
  discovery: DiscoveryDetail;
}

/**
 * atomicNumber দিয়ে extended data খুঁজে বের করার হেল্পার।
 * Phase 2-এ মোডাল কম্পোনেন্ট থেকে এভাবে ব্যবহার হবে:
 *   const ext = getExtendedData(el.atomicNumber);
 *   if (ext) { ... ext.radii.atomic, ext.ionizationEnergies.first ... }
 */
export function getExtendedData(atomicNumber: number): ExtendedElementData | null {
  return extendedElementData[atomicNumber] ?? null;
}

export const extendedElementData: Record<number, ExtendedElementData> = {
  // ── Period 1 ──
  1: {
    radii: { atomic: 53, covalent: 31, ionic: null, vanDerWaals: 120 },
    ionizationEnergies: { first: 1312, second: null, third: null },
    electronAffinity: 73,
    crystalStructure: "হেক্সাগোনাল (কঠিন অবস্থায়)",
    hardnessMohs: null,
    heatOfFusion: 0.117,
    heatOfVaporization: 0.904,
    molarVolume: 11.42,
    notableIsotopes: [
      { symbol: "H-1", type: "stable", abundance: "99.98%" },
      { symbol: "H-2 (ডিউটেরিয়াম)", type: "stable", abundance: "0.02%" },
      { symbol: "H-3 (ট্রিটিয়াম)", type: "radioactive", halfLife: "12.3 বছর" },
    ],
    discovery: {
      place: "ইংল্যান্ড",
      nameOrigin: "গ্রিক 'hydro' (জল) + 'genes' (উৎপাদক) — 'জল উৎপাদনকারী'",
    },
  },
  2: {
    radii: { atomic: 31, covalent: 28, ionic: null, vanDerWaals: 140 },
    ionizationEnergies: { first: 2372, second: 5250, third: null },
    electronAffinity: 0,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (কঠিন, উচ্চ চাপে)",
    hardnessMohs: null,
    heatOfFusion: 0.0138,
    heatOfVaporization: 0.0829,
    molarVolume: 21.0,
    notableIsotopes: [
      { symbol: "He-4", type: "stable", abundance: "99.9999%" },
      { symbol: "He-3", type: "stable", abundance: "0.0001%" },
    ],
    discovery: {
      place: "ফ্রান্স/ইংল্যান্ড (সূর্যের বর্ণালীতে প্রথম শনাক্ত)",
      nameOrigin: "গ্রিক 'helios' (সূর্য) — সূর্যগ্রহণের সময় বর্ণালীতে আবিষ্কৃত",
    },
  },

  // ── Period 2 ──
  3: {
    radii: { atomic: 152, covalent: 128, ionic: 76, vanDerWaals: 182 },
    ionizationEnergies: { first: 520, second: 7298, third: 11815 },
    electronAffinity: 60,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 0.6,
    heatOfFusion: 3.0,
    heatOfVaporization: 136,
    molarVolume: 13.02,
    notableIsotopes: [
      { symbol: "Li-7", type: "stable", abundance: "92.4%" },
      { symbol: "Li-6", type: "stable", abundance: "7.6%" },
    ],
    discovery: {
      place: "সুইডেন",
      nameOrigin: "গ্রিক 'lithos' (পাথর) — খনিজ থেকে আবিষ্কৃত প্রথম ধাতু",
    },
  },
  4: {
    radii: { atomic: 112, covalent: 96, ionic: 45, vanDerWaals: 153 },
    ionizationEnergies: { first: 899, second: 1757, third: 14849 },
    electronAffinity: 0,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 5.5,
    heatOfFusion: 12.2,
    heatOfVaporization: 292,
    molarVolume: 4.85,
    notableIsotopes: [
      { symbol: "Be-9", type: "stable", abundance: "100%" },
    ],
    discovery: {
      place: "ফ্রান্স",
      nameOrigin: "গ্রিক 'beryllos' (বেরিল খনিজ) থেকে",
    },
  },
  5: {
    radii: { atomic: 85, covalent: 84, ionic: 27, vanDerWaals: 192 },
    ionizationEnergies: { first: 801, second: 2427, third: 3660 },
    electronAffinity: 27,
    crystalStructure: "রম্বোহেড্রাল",
    hardnessMohs: 9.3,
    heatOfFusion: 50.2,
    heatOfVaporization: 508,
    molarVolume: 4.39,
    notableIsotopes: [
      { symbol: "B-11", type: "stable", abundance: "80.1%" },
      { symbol: "B-10", type: "stable", abundance: "19.9%" },
    ],
    discovery: {
      place: "ফ্রান্স",
      nameOrigin: "আরবি 'buraq'/ফার্সি 'burah' (বোরাক্স) থেকে",
    },
  },
  6: {
    radii: { atomic: 70, covalent: 76, ionic: 16, vanDerWaals: 170 },
    ionizationEnergies: { first: 1086, second: 2353, third: 4620 },
    electronAffinity: 122,
    crystalStructure: "হেক্সাগোনাল (গ্রাফাইট) / কিউবিক (ডায়মন্ড)",
    hardnessMohs: 10,
    heatOfFusion: 117,
    heatOfVaporization: 715,
    molarVolume: 5.29,
    notableIsotopes: [
      { symbol: "C-12", type: "stable", abundance: "98.93%" },
      { symbol: "C-13", type: "stable", abundance: "1.07%" },
      { symbol: "C-14", type: "radioactive", halfLife: "5,730 বছর" },
    ],
    discovery: {
      place: "প্রাচীনকাল থেকে পরিচিত",
      nameOrigin: "ল্যাটিন 'carbo' (কয়লা)",
    },
  },
  7: {
    radii: { atomic: 65, covalent: 71, ionic: 146, vanDerWaals: 155 },
    ionizationEnergies: { first: 1402, second: 2856, third: 4578 },
    electronAffinity: -7,
    crystalStructure: "হেক্সাগোনাল (কঠিন N₂)",
    hardnessMohs: null,
    heatOfFusion: 0.72,
    heatOfVaporization: 5.57,
    molarVolume: 13.54,
    notableIsotopes: [
      { symbol: "N-14", type: "stable", abundance: "99.64%" },
      { symbol: "N-15", type: "stable", abundance: "0.36%" },
    ],
    discovery: {
      place: "স্কটল্যান্ড",
      nameOrigin: "গ্রিক 'nitron' + 'genes' — 'নাইটার উৎপাদনকারী'",
    },
  },
  8: {
    radii: { atomic: 60, covalent: 66, ionic: 140, vanDerWaals: 152 },
    ionizationEnergies: { first: 1314, second: 3388, third: 5300 },
    electronAffinity: 141,
    crystalStructure: "কিউবিক (কঠিন O₂)",
    hardnessMohs: null,
    heatOfFusion: 0.222,
    heatOfVaporization: 3.41,
    molarVolume: 17.36,
    notableIsotopes: [
      { symbol: "O-16", type: "stable", abundance: "99.76%" },
      { symbol: "O-18", type: "stable", abundance: "0.20%" },
      { symbol: "O-17", type: "stable", abundance: "0.04%" },
    ],
    discovery: {
      place: "সুইডেন/ইংল্যান্ড",
      nameOrigin: "গ্রিক 'oxys' + 'genes' — 'অ্যাসিড উৎপাদনকারী'",
    },
  },
  9: {
    radii: { atomic: 50, covalent: 57, ionic: 133, vanDerWaals: 147 },
    ionizationEnergies: { first: 1681, second: 3374, third: 6050 },
    electronAffinity: 328,
    crystalStructure: "মনোক্লিনিক (কঠিন F₂)",
    hardnessMohs: null,
    heatOfFusion: 0.51,
    heatOfVaporization: 6.62,
    molarVolume: 11.20,
    notableIsotopes: [
      { symbol: "F-19", type: "stable", abundance: "100%" },
    ],
    discovery: {
      place: "ফ্রান্স",
      nameOrigin: "ল্যাটিন 'fluere' (প্রবাহিত হওয়া) — ফ্লুরাইট খনিজ থেকে",
    },
  },
  10: {
    radii: { atomic: 38, covalent: 58, ionic: null, vanDerWaals: 154 },
    ionizationEnergies: { first: 2081, second: 3952, third: 6122 },
    electronAffinity: 0,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC, কঠিন অবস্থায়)",
    hardnessMohs: null,
    heatOfFusion: 0.335,
    heatOfVaporization: 1.71,
    molarVolume: 13.23,
    notableIsotopes: [
      { symbol: "Ne-20", type: "stable", abundance: "90.48%" },
      { symbol: "Ne-22", type: "stable", abundance: "9.25%" },
    ],
    discovery: {
      place: "ইংল্যান্ড",
      nameOrigin: "গ্রিক 'neos' (নতুন)",
    },
  },

  // ── Period 3 ──
  11: {
    radii: { atomic: 186, covalent: 166, ionic: 102, vanDerWaals: 227 },
    ionizationEnergies: { first: 496, second: 4562, third: 6910 },
    electronAffinity: 53,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 0.5,
    heatOfFusion: 2.6,
    heatOfVaporization: 97.7,
    molarVolume: 23.78,
    notableIsotopes: [{ symbol: "Na-23", type: "stable", abundance: "100%" }],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "ইংরেজি 'soda' থেকে; প্রতীক Na ল্যাটিন 'natrium' থেকে" },
  },
  12: {
    radii: { atomic: 160, covalent: 141, ionic: 72, vanDerWaals: 173 },
    ionizationEnergies: { first: 738, second: 1451, third: 7733 },
    electronAffinity: 0,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 2.5,
    heatOfFusion: 8.48,
    heatOfVaporization: 128,
    molarVolume: 13.97,
    notableIsotopes: [
      { symbol: "Mg-24", type: "stable", abundance: "79.0%" },
      { symbol: "Mg-26", type: "stable", abundance: "11.0%" },
      { symbol: "Mg-25", type: "stable", abundance: "10.0%" },
    ],
    discovery: { place: "স্কটল্যান্ড", nameOrigin: "গ্রিসের 'Magnesia' অঞ্চলের নাম থেকে" },
  },
  13: {
    radii: { atomic: 143, covalent: 121, ionic: 53, vanDerWaals: 184 },
    ionizationEnergies: { first: 577, second: 1817, third: 2745 },
    electronAffinity: 42,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 2.75,
    heatOfFusion: 10.7,
    heatOfVaporization: 294,
    molarVolume: 10.0,
    notableIsotopes: [{ symbol: "Al-27", type: "stable", abundance: "100%" }],
    discovery: { place: "ডেনমার্ক", nameOrigin: "ল্যাটিন 'alumen' (ফিটকিরি)" },
  },
  14: {
    radii: { atomic: 111, covalent: 111, ionic: 40, vanDerWaals: 210 },
    ionizationEnergies: { first: 786, second: 1577, third: 3231 },
    electronAffinity: 134,
    crystalStructure: "ডায়মন্ড কিউবিক",
    hardnessMohs: 6.5,
    heatOfFusion: 50.2,
    heatOfVaporization: 359,
    molarVolume: 12.06,
    notableIsotopes: [
      { symbol: "Si-28", type: "stable", abundance: "92.2%" },
      { symbol: "Si-29", type: "stable", abundance: "4.7%" },
      { symbol: "Si-30", type: "stable", abundance: "3.1%" },
    ],
    discovery: { place: "সুইডেন", nameOrigin: "ল্যাটিন 'silex/silicis' (চকমকি পাথর)" },
  },
  15: {
    radii: { atomic: 107, covalent: 107, ionic: 212, vanDerWaals: 180 },
    ionizationEnergies: { first: 1012, second: 1907, third: 2914 },
    electronAffinity: 72,
    crystalStructure: "কিউবিক / ট্রাইক্লিনিক (অ্যালোট্রোপভেদে)",
    hardnessMohs: null,
    heatOfFusion: 0.66,
    heatOfVaporization: 12.4,
    molarVolume: 17.02,
    notableIsotopes: [{ symbol: "P-31", type: "stable", abundance: "100%" }],
    discovery: { place: "জার্মানি", nameOrigin: "গ্রিক 'phosphoros' (আলো বহনকারী) — অন্ধকারে জ্বলে ওঠার কারণে" },
  },
  16: {
    radii: { atomic: 105, covalent: 105, ionic: 184, vanDerWaals: 180 },
    ionizationEnergies: { first: 1000, second: 2252, third: 3357 },
    electronAffinity: 200,
    crystalStructure: "অর্থোরম্বিক",
    hardnessMohs: 2.0,
    heatOfFusion: 1.73,
    heatOfVaporization: 45.0,
    molarVolume: 15.53,
    notableIsotopes: [
      { symbol: "S-32", type: "stable", abundance: "94.99%" },
      { symbol: "S-34", type: "stable", abundance: "4.25%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ল্যাটিন 'sulphurium'" },
  },
  17: {
    radii: { atomic: 102, covalent: 102, ionic: 181, vanDerWaals: 175 },
    ionizationEnergies: { first: 1251, second: 2298, third: 3822 },
    electronAffinity: 349,
    crystalStructure: "অর্থোরম্বিক (কঠিন Cl₂)",
    hardnessMohs: null,
    heatOfFusion: 6.4,
    heatOfVaporization: 20.4,
    molarVolume: 18.7,
    notableIsotopes: [
      { symbol: "Cl-35", type: "stable", abundance: "75.8%" },
      { symbol: "Cl-37", type: "stable", abundance: "24.2%" },
    ],
    discovery: { place: "সুইডেন", nameOrigin: "গ্রিক 'chloros' (হলুদাভ সবুজ)" },
  },
  18: {
    radii: { atomic: 71, covalent: 106, ionic: null, vanDerWaals: 188 },
    ionizationEnergies: { first: 1521, second: 2666, third: 3931 },
    electronAffinity: 0,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC, কঠিন অবস্থায়)",
    hardnessMohs: null,
    heatOfFusion: 1.18,
    heatOfVaporization: 6.5,
    molarVolume: 22.56,
    notableIsotopes: [
      { symbol: "Ar-40", type: "stable", abundance: "99.60%" },
      { symbol: "Ar-36", type: "stable", abundance: "0.34%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'argos' (নিষ্ক্রিয়)" },
  },

  // ── Period 4 ──
  19: {
    radii: { atomic: 227, covalent: 203, ionic: 138, vanDerWaals: 275 },
    ionizationEnergies: { first: 419, second: 3052, third: 4420 },
    electronAffinity: 48,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 0.4,
    heatOfFusion: 2.33,
    heatOfVaporization: 76.9,
    molarVolume: 45.94,
    notableIsotopes: [
      { symbol: "K-39", type: "stable", abundance: "93.3%" },
      { symbol: "K-40", type: "radioactive", halfLife: "১২৫ কোটি বছর" },
      { symbol: "K-41", type: "stable", abundance: "6.7%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "ইংরেজি 'potash'; প্রতীক K ল্যাটিন 'kalium'" },
  },
  20: {
    radii: { atomic: 197, covalent: 176, ionic: 100, vanDerWaals: 231 },
    ionizationEnergies: { first: 590, second: 1145, third: 4912 },
    electronAffinity: 2,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 1.75,
    heatOfFusion: 8.54,
    heatOfVaporization: 154.7,
    molarVolume: 26.2,
    notableIsotopes: [
      { symbol: "Ca-40", type: "stable", abundance: "96.9%" },
      { symbol: "Ca-44", type: "stable", abundance: "2.1%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "ল্যাটিন 'calx' (চুন)" },
  },
  21: {
    radii: { atomic: 162, covalent: 170, ionic: 74.5, vanDerWaals: 211 },
    ionizationEnergies: { first: 633, second: 1235, third: 2389 },
    electronAffinity: 18,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 14.1,
    heatOfVaporization: 314.2,
    molarVolume: 15.0,
    notableIsotopes: [{ symbol: "Sc-45", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইডেন", nameOrigin: "ল্যাটিন 'Scandia' (স্ক্যান্ডিনেভিয়া)" },
  },
  22: {
    radii: { atomic: 147, covalent: 160, ionic: 60.5, vanDerWaals: 187 },
    ionizationEnergies: { first: 658, second: 1310, third: 2652 },
    electronAffinity: 8,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 6.0,
    heatOfFusion: 14.15,
    heatOfVaporization: 425,
    molarVolume: 10.64,
    notableIsotopes: [
      { symbol: "Ti-48", type: "stable", abundance: "73.7%" },
      { symbol: "Ti-46", type: "stable", abundance: "8.3%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক পুরাণের 'Titans'" },
  },
  23: {
    radii: { atomic: 134, covalent: 153, ionic: 54, vanDerWaals: 179 },
    ionizationEnergies: { first: 650, second: 1414, third: 2828 },
    electronAffinity: 51,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 7.0,
    heatOfFusion: 21.5,
    heatOfVaporization: 452,
    molarVolume: 8.32,
    notableIsotopes: [{ symbol: "V-51", type: "stable", abundance: "99.75%" }],
    discovery: { place: "মেক্সিকো/সুইডেন", nameOrigin: "স্ক্যান্ডিনেভীয় দেবী 'Vanadis'" },
  },
  24: {
    radii: { atomic: 128, covalent: 139, ionic: 61.5, vanDerWaals: 189 },
    ionizationEnergies: { first: 653, second: 1592, third: 2987 },
    electronAffinity: 64,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 8.5,
    heatOfFusion: 21.0,
    heatOfVaporization: 347,
    molarVolume: 7.23,
    notableIsotopes: [
      { symbol: "Cr-52", type: "stable", abundance: "83.8%" },
      { symbol: "Cr-53", type: "stable", abundance: "9.5%" },
    ],
    discovery: { place: "ফ্রান্স", nameOrigin: "গ্রিক 'chroma' (রঙ) — যৌগের বহুবর্ণী প্রকৃতির জন্য" },
  },
  25: {
    radii: { atomic: 127, covalent: 139, ionic: 67, vanDerWaals: 197 },
    ionizationEnergies: { first: 717, second: 1509, third: 3248 },
    electronAffinity: 0,
    crystalStructure: "কমপ্লেক্স কিউবিক",
    hardnessMohs: 6.0,
    heatOfFusion: 12.9,
    heatOfVaporization: 221,
    molarVolume: 7.35,
    notableIsotopes: [{ symbol: "Mn-55", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইডেন", nameOrigin: "ল্যাটিন 'magnes' থেকে ম্যাগনেসিয়া খনিজ" },
  },
  26: {
    radii: { atomic: 126, covalent: 132, ionic: 61, vanDerWaals: 194 },
    ionizationEnergies: { first: 762, second: 1562, third: 2957 },
    electronAffinity: 16,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 4.0,
    heatOfFusion: 13.8,
    heatOfVaporization: 340,
    molarVolume: 7.09,
    notableIsotopes: [
      { symbol: "Fe-56", type: "stable", abundance: "91.75%" },
      { symbol: "Fe-54", type: "stable", abundance: "5.85%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ল্যাটিন 'ferrum'" },
  },
  27: {
    radii: { atomic: 125, covalent: 126, ionic: 65, vanDerWaals: 192 },
    ionizationEnergies: { first: 760, second: 1648, third: 3232 },
    electronAffinity: 64,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 5.0,
    heatOfFusion: 16.2,
    heatOfVaporization: 375,
    molarVolume: 6.67,
    notableIsotopes: [{ symbol: "Co-59", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইডেন", nameOrigin: "জার্মান 'kobold' (ভূত/দুষ্ট আত্মা)" },
  },
  28: {
    radii: { atomic: 124, covalent: 124, ionic: 69, vanDerWaals: 163 },
    ionizationEnergies: { first: 737, second: 1753, third: 3395 },
    electronAffinity: 112,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 4.0,
    heatOfFusion: 17.2,
    heatOfVaporization: 378,
    molarVolume: 6.59,
    notableIsotopes: [
      { symbol: "Ni-58", type: "stable", abundance: "68.1%" },
      { symbol: "Ni-60", type: "stable", abundance: "26.2%" },
    ],
    discovery: { place: "সুইডেন", nameOrigin: "জার্মান 'kupfernickel' (শয়তানের তামা)" },
  },
  29: {
    radii: { atomic: 128, covalent: 132, ionic: 77, vanDerWaals: 140 },
    ionizationEnergies: { first: 745, second: 1958, third: 3554 },
    electronAffinity: 118,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 3.0,
    heatOfFusion: 13.1,
    heatOfVaporization: 300,
    molarVolume: 7.11,
    notableIsotopes: [
      { symbol: "Cu-63", type: "stable", abundance: "69.2%" },
      { symbol: "Cu-65", type: "stable", abundance: "30.8%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ল্যাটিন 'cuprum' — সাইপ্রাস দ্বীপ থেকে" },
  },
  30: {
    radii: { atomic: 134, covalent: 122, ionic: 74, vanDerWaals: 139 },
    ionizationEnergies: { first: 906, second: 1733, third: 3833 },
    electronAffinity: 0,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 2.5,
    heatOfFusion: 7.32,
    heatOfVaporization: 115,
    molarVolume: 9.16,
    notableIsotopes: [
      { symbol: "Zn-64", type: "stable", abundance: "49.2%" },
      { symbol: "Zn-66", type: "stable", abundance: "27.7%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত (ভারত)", nameOrigin: "জার্মান 'zink'" },
  },
  31: {
    radii: { atomic: 135, covalent: 122, ionic: 62, vanDerWaals: 187 },
    ionizationEnergies: { first: 579, second: 1979, third: 2963 },
    electronAffinity: 29,
    crystalStructure: "অর্থোরম্বিক",
    hardnessMohs: 1.5,
    heatOfFusion: 5.59,
    heatOfVaporization: 254,
    molarVolume: 11.8,
    notableIsotopes: [
      { symbol: "Ga-69", type: "stable", abundance: "60.1%" },
      { symbol: "Ga-71", type: "stable", abundance: "39.9%" },
    ],
    discovery: { place: "ফ্রান্স", nameOrigin: "ল্যাটিন 'Gallia' (ফ্রান্স)" },
  },
  32: {
    radii: { atomic: 122, covalent: 120, ionic: 53, vanDerWaals: 211 },
    ionizationEnergies: { first: 762, second: 1537, third: 3302 },
    electronAffinity: 119,
    crystalStructure: "ডায়মন্ড কিউবিক",
    hardnessMohs: 6.0,
    heatOfFusion: 36.9,
    heatOfVaporization: 334,
    molarVolume: 13.63,
    notableIsotopes: [
      { symbol: "Ge-74", type: "stable", abundance: "36.7%" },
      { symbol: "Ge-72", type: "stable", abundance: "27.5%" },
    ],
    discovery: { place: "জার্মানি", nameOrigin: "ল্যাটিন 'Germania' (জার্মানি)" },
  },
  33: {
    radii: { atomic: 119, covalent: 119, ionic: 58, vanDerWaals: 185 },
    ionizationEnergies: { first: 947, second: 1798, third: 2735 },
    electronAffinity: 78,
    crystalStructure: "রম্বোহেড্রাল",
    hardnessMohs: 3.5,
    heatOfFusion: 27.7,
    heatOfVaporization: 32.4,
    molarVolume: 12.95,
    notableIsotopes: [{ symbol: "As-75", type: "stable", abundance: "100%" }],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "গ্রিক 'arsenikon' (হলুদ অরপাইমেন্ট)" },
  },
  34: {
    radii: { atomic: 119, covalent: 120, ionic: 191, vanDerWaals: 190 },
    ionizationEnergies: { first: 941, second: 2045, third: 2973 },
    electronAffinity: 195,
    crystalStructure: "হেক্সাগোনাল",
    hardnessMohs: 2.0,
    heatOfFusion: 6.69,
    heatOfVaporization: 95.5,
    molarVolume: 16.42,
    notableIsotopes: [
      { symbol: "Se-80", type: "stable", abundance: "49.6%" },
      { symbol: "Se-78", type: "stable", abundance: "23.8%" },
    ],
    discovery: { place: "সুইডেন", nameOrigin: "গ্রিক 'selene' (চাঁদ)" },
  },
  35: {
    radii: { atomic: 120, covalent: 120, ionic: 196, vanDerWaals: 185 },
    ionizationEnergies: { first: 1140, second: 2103, third: 3470 },
    electronAffinity: 325,
    crystalStructure: "অর্থোরম্বিক (কঠিন Br₂)",
    hardnessMohs: null,
    heatOfFusion: 10.6,
    heatOfVaporization: 29.6,
    molarVolume: 25.6,
    notableIsotopes: [
      { symbol: "Br-79", type: "stable", abundance: "50.7%" },
      { symbol: "Br-81", type: "stable", abundance: "49.3%" },
    ],
    discovery: { place: "ফ্রান্স", nameOrigin: "গ্রিক 'bromos' (দুর্গন্ধ)" },
  },
  36: {
    radii: { atomic: 116, covalent: 116, ionic: null, vanDerWaals: 202 },
    ionizationEnergies: { first: 1351, second: 2350, third: 3565 },
    electronAffinity: 0,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC, কঠিন অবস্থায়)",
    hardnessMohs: null,
    heatOfFusion: 1.64,
    heatOfVaporization: 9.02,
    molarVolume: 27.99,
    notableIsotopes: [
      { symbol: "Kr-84", type: "stable", abundance: "57.0%" },
      { symbol: "Kr-86", type: "stable", abundance: "17.3%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'kryptos' (লুকানো)" },
  },

  // ── Period 5 ──
  37: {
    radii: { atomic: 248, covalent: 220, ionic: 152, vanDerWaals: 303 },
    ionizationEnergies: { first: 403, second: 2633, third: 3860 },
    electronAffinity: 47,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 0.3,
    heatOfFusion: 2.19,
    heatOfVaporization: 69.0,
    molarVolume: 55.76,
    notableIsotopes: [
      { symbol: "Rb-85", type: "stable", abundance: "72.2%" },
      { symbol: "Rb-87", type: "radioactive", halfLife: "৪৯০০ কোটি বছর" },
    ],
    discovery: { place: "জার্মানি", nameOrigin: "ল্যাটিন 'rubidus' (গাঢ় লাল) — বর্ণালী রেখার রঙ" },
  },
  38: {
    radii: { atomic: 215, covalent: 195, ionic: 118, vanDerWaals: 249 },
    ionizationEnergies: { first: 549, second: 1064, third: 4138 },
    electronAffinity: 5,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: null,
    heatOfFusion: 8.0,
    heatOfVaporization: 137,
    molarVolume: 33.94,
    notableIsotopes: [
      { symbol: "Sr-88", type: "stable", abundance: "82.6%" },
      { symbol: "Sr-86", type: "stable", abundance: "9.9%" },
    ],
    discovery: { place: "স্কটল্যান্ড", nameOrigin: "স্কটল্যান্ডের 'Strontian' গ্রাম" },
  },
  39: {
    radii: { atomic: 180, covalent: 190, ionic: 90, vanDerWaals: 219 },
    ionizationEnergies: { first: 600, second: 1180, third: 1980 },
    electronAffinity: 30,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 11.4,
    heatOfVaporization: 365,
    molarVolume: 19.88,
    notableIsotopes: [{ symbol: "Y-89", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইডেন", nameOrigin: "সুইডেনের 'Ytterby' গ্রাম" },
  },
  40: {
    radii: { atomic: 160, covalent: 175, ionic: 72, vanDerWaals: 186 },
    ionizationEnergies: { first: 640, second: 1267, third: 2218 },
    electronAffinity: 41,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 5.0,
    heatOfFusion: 21.0,
    heatOfVaporization: 573,
    molarVolume: 14.02,
    notableIsotopes: [
      { symbol: "Zr-90", type: "stable", abundance: "51.5%" },
      { symbol: "Zr-94", type: "stable", abundance: "17.4%" },
    ],
    discovery: { place: "জার্মানি", nameOrigin: "আরবি 'zargun' (স্বর্ণাভ) — জিরকন খনিজ থেকে" },
  },
  41: {
    radii: { atomic: 146, covalent: 164, ionic: 64, vanDerWaals: 207 },
    ionizationEnergies: { first: 652, second: 1380, third: 2416 },
    electronAffinity: 86,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 6.0,
    heatOfFusion: 30.0,
    heatOfVaporization: 690,
    molarVolume: 10.83,
    notableIsotopes: [{ symbol: "Nb-93", type: "stable", abundance: "100%" }],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক পুরাণের 'Niobe'" },
  },
  42: {
    radii: { atomic: 139, covalent: 154, ionic: 59, vanDerWaals: 209 },
    ionizationEnergies: { first: 684, second: 1560, third: 2618 },
    electronAffinity: 72,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 5.5,
    heatOfFusion: 37.5,
    heatOfVaporization: 598,
    molarVolume: 9.38,
    notableIsotopes: [
      { symbol: "Mo-98", type: "stable", abundance: "24.1%" },
      { symbol: "Mo-96", type: "stable", abundance: "16.7%" },
    ],
    discovery: { place: "সুইডেন", nameOrigin: "গ্রিক 'molybdos' (সীসা) — সীসা আকরিকের সাথে বিভ্রান্তির কারণে" },
  },
  43: {
    radii: { atomic: 136, covalent: 147, ionic: 56, vanDerWaals: 209 },
    ionizationEnergies: { first: 702, second: 1470, third: 2850 },
    electronAffinity: 53,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 33.3,
    heatOfVaporization: 585,
    molarVolume: 8.63,
    notableIsotopes: [{ symbol: "Tc-98 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৪২ লক্ষ বছর" }],
    discovery: { place: "ইতালি", nameOrigin: "গ্রিক 'technetos' (কৃত্রিম) — প্রথম কৃত্রিম মৌল" },
  },
  44: {
    radii: { atomic: 134, covalent: 146, ionic: 62, vanDerWaals: 207 },
    ionizationEnergies: { first: 710, second: 1620, third: 2747 },
    electronAffinity: 101,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 6.5,
    heatOfFusion: 38.0,
    heatOfVaporization: 595,
    molarVolume: 8.17,
    notableIsotopes: [
      { symbol: "Ru-102", type: "stable", abundance: "31.6%" },
      { symbol: "Ru-104", type: "stable", abundance: "18.6%" },
    ],
    discovery: { place: "রাশিয়া", nameOrigin: "ল্যাটিন 'Ruthenia' (রাশিয়া)" },
  },
  45: {
    radii: { atomic: 134, covalent: 142, ionic: 66.5, vanDerWaals: 195 },
    ionizationEnergies: { first: 720, second: 1740, third: 2997 },
    electronAffinity: 110,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 6.0,
    heatOfFusion: 26.6,
    heatOfVaporization: 494,
    molarVolume: 8.28,
    notableIsotopes: [{ symbol: "Rh-103", type: "stable", abundance: "100%" }],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'rhodon' (গোলাপ) — গোলাপি লবণের রঙ থেকে" },
  },
  46: {
    radii: { atomic: 137, covalent: 139, ionic: 86, vanDerWaals: 202 },
    ionizationEnergies: { first: 804, second: 1875, third: 3177 },
    electronAffinity: 54,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 4.75,
    heatOfFusion: 16.7,
    heatOfVaporization: 358,
    molarVolume: 8.56,
    notableIsotopes: [
      { symbol: "Pd-106", type: "stable", abundance: "27.3%" },
      { symbol: "Pd-108", type: "stable", abundance: "26.5%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রহাণু 'Pallas' থেকে" },
  },
  47: {
    radii: { atomic: 144, covalent: 145, ionic: 115, vanDerWaals: 172 },
    ionizationEnergies: { first: 731, second: 2070, third: 3361 },
    electronAffinity: 126,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 2.5,
    heatOfFusion: 11.3,
    heatOfVaporization: 258,
    molarVolume: 10.27,
    notableIsotopes: [
      { symbol: "Ag-107", type: "stable", abundance: "51.8%" },
      { symbol: "Ag-109", type: "stable", abundance: "48.2%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ইংরেজি 'silver'; প্রতীক Ag ল্যাটিন 'argentum'" },
  },
  48: {
    radii: { atomic: 151, covalent: 144, ionic: 95, vanDerWaals: 158 },
    ionizationEnergies: { first: 868, second: 1631, third: 3616 },
    electronAffinity: 0,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 2.0,
    heatOfFusion: 6.21,
    heatOfVaporization: 100,
    molarVolume: 13.0,
    notableIsotopes: [
      { symbol: "Cd-114", type: "stable", abundance: "28.7%" },
      { symbol: "Cd-112", type: "stable", abundance: "24.1%" },
    ],
    discovery: { place: "জার্মানি", nameOrigin: "ল্যাটিন 'cadmia' (দস্তা আকরিক)" },
  },
  49: {
    radii: { atomic: 167, covalent: 142, ionic: 80, vanDerWaals: 193 },
    ionizationEnergies: { first: 558, second: 1821, third: 2704 },
    electronAffinity: 29,
    crystalStructure: "টেট্রাগোনাল",
    hardnessMohs: 1.2,
    heatOfFusion: 3.26,
    heatOfVaporization: 232,
    molarVolume: 15.76,
    notableIsotopes: [{ symbol: "In-115", type: "radioactive", halfLife: "৪৪১ লক্ষ কোটি বছর (প্রায় স্থিতিশীল)" }],
    discovery: { place: "জার্মানি", nameOrigin: "বর্ণালীতে নীল (indigo) রেখার জন্য" },
  },
  50: {
    radii: { atomic: 140, covalent: 139, ionic: 69, vanDerWaals: 217 },
    ionizationEnergies: { first: 709, second: 1412, third: 2943 },
    electronAffinity: 107,
    crystalStructure: "টেট্রাগোনাল",
    hardnessMohs: 1.5,
    heatOfFusion: 7.03,
    heatOfVaporization: 296,
    molarVolume: 16.29,
    notableIsotopes: [
      { symbol: "Sn-120", type: "stable", abundance: "32.6%" },
      { symbol: "Sn-118", type: "stable", abundance: "24.2%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ল্যাটিন 'stannum'" },
  },
  51: {
    radii: { atomic: 145, covalent: 139, ionic: 76, vanDerWaals: 206 },
    ionizationEnergies: { first: 834, second: 1595, third: 2440 },
    electronAffinity: 101,
    crystalStructure: "রম্বোহেড্রাল",
    hardnessMohs: 3.0,
    heatOfFusion: 19.7,
    heatOfVaporization: 193,
    molarVolume: 18.19,
    notableIsotopes: [
      { symbol: "Sb-121", type: "stable", abundance: "57.2%" },
      { symbol: "Sb-123", type: "stable", abundance: "42.8%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "গ্রিক 'anti + monos' (একা নয়); প্রতীক Sb ল্যাটিন 'stibium'" },
  },
  52: {
    radii: { atomic: 140, covalent: 138, ionic: 221, vanDerWaals: 206 },
    ionizationEnergies: { first: 869, second: 1790, third: 2698 },
    electronAffinity: 190,
    crystalStructure: "হেক্সাগোনাল",
    hardnessMohs: 2.25,
    heatOfFusion: 17.5,
    heatOfVaporization: 114.1,
    molarVolume: 20.46,
    notableIsotopes: [
      { symbol: "Te-130", type: "stable", abundance: "34.1%" },
      { symbol: "Te-128", type: "stable", abundance: "31.7%" },
    ],
    discovery: { place: "রোমানিয়া (ট্রান্সিলভানিয়া)", nameOrigin: "ল্যাটিন 'tellus' (পৃথিবী)" },
  },
  53: {
    radii: { atomic: 140, covalent: 139, ionic: 220, vanDerWaals: 198 },
    ionizationEnergies: { first: 1008, second: 1846, third: 3200 },
    electronAffinity: 295,
    crystalStructure: "অর্থোরম্বিক",
    hardnessMohs: null,
    heatOfFusion: 15.5,
    heatOfVaporization: 41.6,
    molarVolume: 25.72,
    notableIsotopes: [{ symbol: "I-127", type: "stable", abundance: "100%" }],
    discovery: { place: "ফ্রান্স", nameOrigin: "গ্রিক 'iodes' (বেগুনি)" },
  },
  54: {
    radii: { atomic: 130, covalent: 140, ionic: 62, vanDerWaals: 216 },
    ionizationEnergies: { first: 1170, second: 2046, third: 3099 },
    electronAffinity: 0,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC, কঠিন অবস্থায়)",
    hardnessMohs: null,
    heatOfFusion: 2.27,
    heatOfVaporization: 12.64,
    molarVolume: 35.92,
    notableIsotopes: [
      { symbol: "Xe-132", type: "stable", abundance: "26.9%" },
      { symbol: "Xe-129", type: "stable", abundance: "26.4%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'xenos' (আগন্তুক)" },
  },

  // ── Period 6 (Cs–Lu) ──
  55: {
    radii: { atomic: 265, covalent: 244, ionic: 167, vanDerWaals: 343 },
    ionizationEnergies: { first: 376, second: 2234, third: 3400 },
    electronAffinity: 46,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 0.2,
    heatOfFusion: 2.09,
    heatOfVaporization: 63.9,
    molarVolume: 70.94,
    notableIsotopes: [{ symbol: "Cs-133", type: "stable", abundance: "100%" }],
    discovery: { place: "জার্মানি", nameOrigin: "ল্যাটিন 'caesius' (আকাশি নীল) — বর্ণালী রেখার রঙ" },
  },
  56: {
    radii: { atomic: 222, covalent: 215, ionic: 135, vanDerWaals: 268 },
    ionizationEnergies: { first: 503, second: 965, third: 3600 },
    electronAffinity: 14,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: null,
    heatOfFusion: 7.66,
    heatOfVaporization: 142,
    molarVolume: 38.16,
    notableIsotopes: [
      { symbol: "Ba-138", type: "stable", abundance: "71.7%" },
      { symbol: "Ba-137", type: "stable", abundance: "11.2%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'barys' (ভারী)" },
  },
  57: {
    radii: { atomic: 187, covalent: 207, ionic: 103.2, vanDerWaals: 240 },
    ionizationEnergies: { first: 538, second: 1067, third: 1850 },
    electronAffinity: 45,
    crystalStructure: "হেক্সাগোনাল",
    hardnessMohs: null,
    heatOfFusion: 6.2,
    heatOfVaporization: 400,
    molarVolume: 22.39,
    notableIsotopes: [{ symbol: "La-139", type: "stable", abundance: "99.91%" }],
    discovery: { place: "সুইডেন", nameOrigin: "গ্রিক 'lanthanein' (লুকিয়ে থাকা)" },
  },
  58: {
    radii: { atomic: 182, covalent: 204, ionic: 101, vanDerWaals: 235 },
    ionizationEnergies: { first: 534, second: 1050, third: 1949 },
    electronAffinity: 55,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: null,
    heatOfFusion: 5.46,
    heatOfVaporization: 398,
    molarVolume: 21.0,
    notableIsotopes: [{ symbol: "Ce-140", type: "stable", abundance: "88.4%" }],
    discovery: { place: "সুইডেন", nameOrigin: "গ্রহাণু 'Ceres'" },
  },
  59: {
    radii: { atomic: 182, covalent: 203, ionic: 99, vanDerWaals: 239 },
    ionizationEnergies: { first: 527, second: 1020, third: 2086 },
    electronAffinity: 93,
    crystalStructure: "হেক্সাগোনাল",
    hardnessMohs: null,
    heatOfFusion: 6.9,
    heatOfVaporization: 331,
    molarVolume: 20.8,
    notableIsotopes: [{ symbol: "Pr-141", type: "stable", abundance: "100%" }],
    discovery: { place: "অস্ট্রিয়া", nameOrigin: "গ্রিক 'prasios + didymos' (সবুজ জোড়া)" },
  },
  60: {
    radii: { atomic: 181, covalent: 201, ionic: 98.3, vanDerWaals: 229 },
    ionizationEnergies: { first: 533, second: 1040, third: 2130 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল",
    hardnessMohs: null,
    heatOfFusion: 7.1,
    heatOfVaporization: 289,
    molarVolume: 20.6,
    notableIsotopes: [
      { symbol: "Nd-142", type: "stable", abundance: "27.2%" },
      { symbol: "Nd-144", type: "radioactive", halfLife: "২৩৮ কোটি কোটি বছর" },
    ],
    discovery: { place: "অস্ট্রিয়া", nameOrigin: "গ্রিক 'neos + didymos' (নতুন জোড়া)" },
  },
  61: {
    radii: { atomic: 183, covalent: 199, ionic: 97, vanDerWaals: 236 },
    ionizationEnergies: { first: 540, second: 1050, third: 2150 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল",
    hardnessMohs: null,
    heatOfFusion: 7.7,
    heatOfVaporization: 289,
    molarVolume: 20.23,
    notableIsotopes: [{ symbol: "Pm-145 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১৭.৭ বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "গ্রিক পুরাণের 'Prometheus'" },
  },
  62: {
    radii: { atomic: 180, covalent: 198, ionic: 95.8, vanDerWaals: 229 },
    ionizationEnergies: { first: 545, second: 1070, third: 2260 },
    electronAffinity: 50,
    crystalStructure: "রম্বোহেড্রাল",
    hardnessMohs: null,
    heatOfFusion: 8.62,
    heatOfVaporization: 192,
    molarVolume: 19.98,
    notableIsotopes: [
      { symbol: "Sm-152", type: "stable", abundance: "26.7%" },
      { symbol: "Sm-154", type: "stable", abundance: "22.7%" },
    ],
    discovery: { place: "ফ্রান্স", nameOrigin: "খনিজ 'samarskite' থেকে" },
  },
  63: {
    radii: { atomic: 180, covalent: 198, ionic: 94.7, vanDerWaals: 233 },
    ionizationEnergies: { first: 547, second: 1085, third: 2404 },
    electronAffinity: 50,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: null,
    heatOfFusion: 10.5,
    heatOfVaporization: 176,
    molarVolume: 28.97,
    notableIsotopes: [
      { symbol: "Eu-153", type: "stable", abundance: "52.2%" },
      { symbol: "Eu-151", type: "stable", abundance: "47.8%" },
    ],
    discovery: { place: "ফ্রান্স", nameOrigin: "মহাদেশ 'Europe' থেকে" },
  },
  64: {
    radii: { atomic: 180, covalent: 196, ionic: 93.8, vanDerWaals: 237 },
    ionizationEnergies: { first: 594, second: 1170, third: 1990 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 10.05,
    heatOfVaporization: 301.3,
    molarVolume: 19.9,
    notableIsotopes: [
      { symbol: "Gd-158", type: "stable", abundance: "24.8%" },
      { symbol: "Gd-160", type: "stable", abundance: "21.9%" },
    ],
    discovery: { place: "সুইজারল্যান্ড", nameOrigin: "বিজ্ঞানী Johan Gadolin এর নামে" },
  },
  65: {
    radii: { atomic: 177, covalent: 194, ionic: 92.3, vanDerWaals: 221 },
    ionizationEnergies: { first: 566, second: 1112, third: 2114 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 10.15,
    heatOfVaporization: 391,
    molarVolume: 19.34,
    notableIsotopes: [{ symbol: "Tb-159", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইডেন", nameOrigin: "সুইডেনের 'Ytterby' গ্রাম" },
  },
  66: {
    radii: { atomic: 178, covalent: 192, ionic: 91.2, vanDerWaals: 229 },
    ionizationEnergies: { first: 573, second: 1126, third: 2200 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 11.06,
    heatOfVaporization: 290,
    molarVolume: 19.0,
    notableIsotopes: [
      { symbol: "Dy-164", type: "stable", abundance: "28.2%" },
      { symbol: "Dy-162", type: "stable", abundance: "25.5%" },
    ],
    discovery: { place: "ফ্রান্স", nameOrigin: "গ্রিক 'dysprositos' (পাওয়া কঠিন)" },
  },
  67: {
    radii: { atomic: 176, covalent: 192, ionic: 90.1, vanDerWaals: 216 },
    ionizationEnergies: { first: 581, second: 1139, third: 2204 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 17.0,
    heatOfVaporization: 251,
    molarVolume: 18.75,
    notableIsotopes: [{ symbol: "Ho-165", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইজারল্যান্ড/সুইডেন", nameOrigin: "স্টকহোমের ল্যাটিন নাম 'Holmia'" },
  },
  68: {
    radii: { atomic: 176, covalent: 189, ionic: 89, vanDerWaals: 235 },
    ionizationEnergies: { first: 589, second: 1150, third: 2194 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 19.9,
    heatOfVaporization: 293,
    molarVolume: 18.4,
    notableIsotopes: [
      { symbol: "Er-166", type: "stable", abundance: "33.5%" },
      { symbol: "Er-168", type: "stable", abundance: "27.0%" },
    ],
    discovery: { place: "সুইডেন", nameOrigin: "সুইডেনের 'Ytterby' গ্রাম" },
  },
  69: {
    radii: { atomic: 176, covalent: 190, ionic: 88, vanDerWaals: 227 },
    ionizationEnergies: { first: 597, second: 1163, third: 2285 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 16.8,
    heatOfVaporization: 191,
    molarVolume: 18.1,
    notableIsotopes: [{ symbol: "Tm-169", type: "stable", abundance: "100%" }],
    discovery: { place: "সুইডেন", nameOrigin: "স্ক্যান্ডিনেভিয়ার প্রাচীন নাম 'Thule'" },
  },
  70: {
    radii: { atomic: 176, covalent: 187, ionic: 86.8, vanDerWaals: 242 },
    ionizationEnergies: { first: 603, second: 1175, third: 2417 },
    electronAffinity: 50,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: null,
    heatOfFusion: 7.66,
    heatOfVaporization: 129,
    molarVolume: 24.79,
    notableIsotopes: [
      { symbol: "Yb-174", type: "stable", abundance: "31.8%" },
      { symbol: "Yb-172", type: "stable", abundance: "21.8%" },
    ],
    discovery: { place: "সুইজারল্যান্ড", nameOrigin: "সুইডেনের 'Ytterby' গ্রাম" },
  },
  71: {
    radii: { atomic: 174, covalent: 187, ionic: 86.1, vanDerWaals: 221 },
    ionizationEnergies: { first: 524, second: 1340, third: 2022 },
    electronAffinity: 50,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: null,
    heatOfFusion: 18.6,
    heatOfVaporization: 414,
    molarVolume: 17.78,
    notableIsotopes: [{ symbol: "Lu-175", type: "stable", abundance: "97.4%" }],
    discovery: { place: "ফ্রান্স", nameOrigin: "প্যারিসের প্রাচীন নাম 'Lutetia'" },
  },

  // ── Period 6 (Hf–Rn) ──
  72: {
    radii: { atomic: 159, covalent: 175, ionic: 71, vanDerWaals: 212 },
    ionizationEnergies: { first: 659, second: 1440, third: 2250 },
    electronAffinity: 0,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 5.5,
    heatOfFusion: 27.2,
    heatOfVaporization: 648,
    molarVolume: 13.44,
    notableIsotopes: [
      { symbol: "Hf-180", type: "stable", abundance: "35.1%" },
      { symbol: "Hf-178", type: "stable", abundance: "27.3%" },
    ],
    discovery: { place: "ডেনমার্ক", nameOrigin: "কোপেনহেগেনের ল্যাটিন নাম 'Hafnia'" },
  },
  73: {
    radii: { atomic: 146, covalent: 170, ionic: 64, vanDerWaals: 217 },
    ionizationEnergies: { first: 761, second: 1500, third: 2100 },
    electronAffinity: 31,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 6.5,
    heatOfFusion: 36.6,
    heatOfVaporization: 732.8,
    molarVolume: 10.85,
    notableIsotopes: [{ symbol: "Ta-181", type: "stable", abundance: "99.99%" }],
    discovery: { place: "সুইডেন", nameOrigin: "গ্রিক পুরাণের 'Tantalus'" },
  },
  74: {
    radii: { atomic: 139, covalent: 162, ionic: 60, vanDerWaals: 210 },
    ionizationEnergies: { first: 770, second: 1700, third: 2300 },
    electronAffinity: 79,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: 7.5,
    heatOfFusion: 52.3,
    heatOfVaporization: 806.7,
    molarVolume: 9.47,
    notableIsotopes: [
      { symbol: "W-184", type: "stable", abundance: "30.6%" },
      { symbol: "W-186", type: "stable", abundance: "28.4%" },
    ],
    discovery: { place: "স্পেন", nameOrigin: "সুইডিশ 'tung sten' (ভারী পাথর); প্রতীক W 'wolfram'" },
  },
  75: {
    radii: { atomic: 137, covalent: 151, ionic: 53, vanDerWaals: 217 },
    ionizationEnergies: { first: 760, second: 1260, third: 2510 },
    electronAffinity: 14,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 7.0,
    heatOfFusion: 60.43,
    heatOfVaporization: 704,
    molarVolume: 8.86,
    notableIsotopes: [
      { symbol: "Re-187", type: "radioactive", halfLife: "৪১৬০ কোটি বছর" },
      { symbol: "Re-185", type: "stable", abundance: "37.4%" },
    ],
    discovery: { place: "জার্মানি", nameOrigin: "ল্যাটিন 'Rhenus' (রাইন নদী)" },
  },
  76: {
    radii: { atomic: 135, covalent: 144, ionic: 63, vanDerWaals: 216 },
    ionizationEnergies: { first: 840, second: 1600, third: 2400 },
    electronAffinity: 106,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 7.0,
    heatOfFusion: 57.85,
    heatOfVaporization: 738,
    molarVolume: 8.42,
    notableIsotopes: [
      { symbol: "Os-192", type: "stable", abundance: "40.8%" },
      { symbol: "Os-190", type: "stable", abundance: "26.3%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'osme' (গন্ধ) — অক্সাইডের তীব্র গন্ধ" },
  },
  77: {
    radii: { atomic: 136, covalent: 141, ionic: 68, vanDerWaals: 202 },
    ionizationEnergies: { first: 880, second: 1600, third: 2600 },
    electronAffinity: 151,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 6.5,
    heatOfFusion: 41.12,
    heatOfVaporization: 604,
    molarVolume: 8.52,
    notableIsotopes: [
      { symbol: "Ir-193", type: "stable", abundance: "62.7%" },
      { symbol: "Ir-191", type: "stable", abundance: "37.3%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক দেবী 'Iris' (রংধনু) — লবণের বহুবর্ণী প্রকৃতি" },
  },
  78: {
    radii: { atomic: 139, covalent: 136, ionic: 80, vanDerWaals: 209 },
    ionizationEnergies: { first: 870, second: 1791, third: 2800 },
    electronAffinity: 205,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 4.0,
    heatOfFusion: 22.17,
    heatOfVaporization: 469,
    molarVolume: 9.09,
    notableIsotopes: [
      { symbol: "Pt-195", type: "stable", abundance: "33.8%" },
      { symbol: "Pt-194", type: "stable", abundance: "32.9%" },
    ],
    discovery: { place: "দক্ষিণ আমেরিকা/স্পেন", nameOrigin: "স্প্যানিশ 'platina' (ছোট রূপা)" },
  },
  79: {
    radii: { atomic: 144, covalent: 136, ionic: 137, vanDerWaals: 166 },
    ionizationEnergies: { first: 890, second: 1980, third: 2900 },
    electronAffinity: 223,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 2.5,
    heatOfFusion: 12.55,
    heatOfVaporization: 324,
    molarVolume: 10.21,
    notableIsotopes: [{ symbol: "Au-197", type: "stable", abundance: "100%" }],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ইংরেজি 'gold'; প্রতীক Au ল্যাটিন 'aurum'" },
  },
  80: {
    radii: { atomic: 151, covalent: 132, ionic: 119, vanDerWaals: 155 },
    ionizationEnergies: { first: 1007, second: 1810, third: 3300 },
    electronAffinity: 0,
    crystalStructure: "রম্বোহেড্রাল",
    hardnessMohs: null,
    heatOfFusion: 2.29,
    heatOfVaporization: 59.2,
    molarVolume: 14.09,
    notableIsotopes: [
      { symbol: "Hg-202", type: "stable", abundance: "29.9%" },
      { symbol: "Hg-200", type: "stable", abundance: "23.1%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "রোমান দেবতা 'Mercury'; প্রতীক Hg গ্রিক 'hydrargyrum' (তরল রূপা)" },
  },
  81: {
    radii: { atomic: 170, covalent: 145, ionic: 150, vanDerWaals: 196 },
    ionizationEnergies: { first: 589, second: 1971, third: 2878 },
    electronAffinity: 19,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড (HCP)",
    hardnessMohs: 1.2,
    heatOfFusion: 4.14,
    heatOfVaporization: 165,
    molarVolume: 17.22,
    notableIsotopes: [
      { symbol: "Tl-205", type: "stable", abundance: "70.5%" },
      { symbol: "Tl-203", type: "stable", abundance: "29.5%" },
    ],
    discovery: { place: "ইংল্যান্ড", nameOrigin: "গ্রিক 'thallos' (সবুজ কুঁড়ি) — বর্ণালী রেখার রঙ" },
  },
  82: {
    radii: { atomic: 175, covalent: 146, ionic: 119, vanDerWaals: 202 },
    ionizationEnergies: { first: 716, second: 1450, third: 3081 },
    electronAffinity: 35,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 1.5,
    heatOfFusion: 4.77,
    heatOfVaporization: 179.5,
    molarVolume: 18.26,
    notableIsotopes: [
      { symbol: "Pb-208", type: "stable", abundance: "52.4%" },
      { symbol: "Pb-206", type: "stable", abundance: "24.1%" },
    ],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত", nameOrigin: "ইংরেজি 'lead'; প্রতীক Pb ল্যাটিন 'plumbum'" },
  },
  83: {
    radii: { atomic: 154, covalent: 148, ionic: 103, vanDerWaals: 207 },
    ionizationEnergies: { first: 703, second: 1610, third: 2466 },
    electronAffinity: 91,
    crystalStructure: "রম্বোহেড্রাল",
    hardnessMohs: 2.25,
    heatOfFusion: 11.0,
    heatOfVaporization: 179,
    molarVolume: 21.31,
    notableIsotopes: [{ symbol: "Bi-209", type: "radioactive", halfLife: "২০০ কোটি কোটি বছর (কার্যত স্থিতিশীল)" }],
    discovery: { place: "প্রাচীনকাল থেকে পরিচিত (স্বীকৃত ১৭৫৩)", nameOrigin: "জার্মান 'Wismuth'" },
  },
  84: {
    radii: { atomic: 168, covalent: 140, ionic: 94, vanDerWaals: 197 },
    ionizationEnergies: { first: 812, second: null, third: null },
    electronAffinity: 183,
    crystalStructure: "কিউবিক",
    hardnessMohs: null,
    heatOfFusion: 13.0,
    heatOfVaporization: 100.8,
    molarVolume: 22.97,
    notableIsotopes: [{ symbol: "Po-209 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১০২ বছর" }],
    discovery: { place: "ফ্রান্স/পোল্যান্ড", nameOrigin: "ম্যারি কুরির জন্মভূমি 'Poland' থেকে" },
  },
  85: {
    radii: { atomic: 202, covalent: 150, ionic: null, vanDerWaals: 202 },
    ionizationEnergies: { first: 920, second: null, third: null },
    electronAffinity: 270,
    crystalStructure: "অজানা (অত্যন্ত অল্প পরিমাণে পাওয়া যায়)",
    hardnessMohs: null,
    heatOfFusion: 6.0,
    heatOfVaporization: 40.0,
    molarVolume: null,
    notableIsotopes: [{ symbol: "At-210 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৮.১ ঘণ্টা" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "গ্রিক 'astatos' (অস্থিতিশীল)" },
  },
  86: {
    radii: { atomic: 220, covalent: 150, ionic: null, vanDerWaals: 220 },
    ionizationEnergies: { first: 1037, second: null, third: null },
    electronAffinity: 0,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC, কঠিন অবস্থায়)",
    hardnessMohs: null,
    heatOfFusion: 3.25,
    heatOfVaporization: 18.1,
    molarVolume: 50.5,
    notableIsotopes: [{ symbol: "Rn-222 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৩.৮ দিন" }],
    discovery: { place: "জার্মানি", nameOrigin: "'রেডিয়াম' থেকে নির্গত গ্যাস হওয়ায়" },
  },

  // ── Period 7 (Fr–No) ──
  87: {
    radii: { atomic: 348, covalent: 260, ionic: 180, vanDerWaals: null },
    ionizationEnergies: { first: 380, second: null, third: null },
    electronAffinity: 47,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (অনুমিত)",
    hardnessMohs: null,
    heatOfFusion: 2.0,
    heatOfVaporization: 65,
    molarVolume: null,
    notableIsotopes: [{ symbol: "Fr-223 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "২২ মিনিট" }],
    discovery: { place: "ফ্রান্স", nameOrigin: "আবিষ্কারকের দেশ 'France'" },
  },
  88: {
    radii: { atomic: 283, covalent: 221, ionic: 148, vanDerWaals: null },
    ionizationEnergies: { first: 509, second: 979, third: null },
    electronAffinity: 10,
    crystalStructure: "বডি-সেন্টার্ড কিউবিক (BCC)",
    hardnessMohs: null,
    heatOfFusion: 8.5,
    heatOfVaporization: 113,
    molarVolume: 41.09,
    notableIsotopes: [{ symbol: "Ra-226 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১৬০০ বছর" }],
    discovery: { place: "ফ্রান্স (মেরি ও পিয়ের কুরি)", nameOrigin: "ল্যাটিন 'radius' (রশ্মি) — তেজস্ক্রিয়তার কারণে" },
  },
  89: {
    radii: { atomic: 260, covalent: 215, ionic: 118, vanDerWaals: null },
    ionizationEnergies: { first: 499, second: 1170, third: 1900 },
    electronAffinity: 33,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: null,
    heatOfFusion: 14.0,
    heatOfVaporization: 400,
    molarVolume: 22.55,
    notableIsotopes: [{ symbol: "Ac-227 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "২১.৮ বছর" }],
    discovery: { place: "ফ্রান্স", nameOrigin: "গ্রিক 'aktis' (রশ্মি)" },
  },
  90: {
    radii: { atomic: 237, covalent: 206, ionic: 101, vanDerWaals: null },
    ionizationEnergies: { first: 587, second: 1110, third: 1930 },
    electronAffinity: null,
    crystalStructure: "ফেস-সেন্টার্ড কিউবিক (FCC)",
    hardnessMohs: 3.0,
    heatOfFusion: 13.81,
    heatOfVaporization: 514,
    molarVolume: 19.8,
    notableIsotopes: [{ symbol: "Th-232", type: "radioactive", halfLife: "১৪০০ কোটি বছর" }],
    discovery: { place: "নরওয়ে/সুইডেন", nameOrigin: "নরওয়েজীয় দেবতা 'Thor'" },
  },
  91: {
    radii: { atomic: 243, covalent: 200, ionic: 104, vanDerWaals: null },
    ionizationEnergies: { first: 568, second: 1128, third: 1786 },
    electronAffinity: null,
    crystalStructure: "টেট্রাগোনাল",
    hardnessMohs: null,
    heatOfFusion: 12.34,
    heatOfVaporization: 481,
    molarVolume: 15.18,
    notableIsotopes: [{ symbol: "Pa-231 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৩২,৭০০ বছর" }],
    discovery: { place: "জার্মানি/ইংল্যান্ড", nameOrigin: "গ্রিক 'proto + actinium' (অ্যাক্টিনিয়ামের পূর্বসূরি)" },
  },
  92: {
    radii: { atomic: 242, covalent: 196, ionic: 89, vanDerWaals: 186 },
    ionizationEnergies: { first: 598, second: 1420, third: null },
    electronAffinity: null,
    crystalStructure: "অর্থোরম্বিক",
    hardnessMohs: 6.0,
    heatOfFusion: 9.14,
    heatOfVaporization: 417.1,
    molarVolume: 12.49,
    notableIsotopes: [
      { symbol: "U-238", type: "radioactive", halfLife: "৪৪৭ কোটি বছর" },
      { symbol: "U-235", type: "radioactive", halfLife: "৭০ কোটি বছর" },
    ],
    discovery: { place: "জার্মানি", nameOrigin: "গ্রহ 'Uranus'" },
  },
  93: {
    radii: { atomic: 239, covalent: 190, ionic: 95, vanDerWaals: null },
    ionizationEnergies: { first: 605, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অর্থোরম্বিক",
    hardnessMohs: null,
    heatOfFusion: 9.46,
    heatOfVaporization: 336,
    molarVolume: 21.1,
    notableIsotopes: [{ symbol: "Np-237 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "২১ লক্ষ বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "গ্রহ 'Neptune'" },
  },
  94: {
    radii: { atomic: 240, covalent: 187, ionic: 90, vanDerWaals: null },
    ionizationEnergies: { first: 585, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "মনোক্লিনিক",
    hardnessMohs: null,
    heatOfFusion: 2.82,
    heatOfVaporization: 333.5,
    molarVolume: 12.29,
    notableIsotopes: [{ symbol: "Pu-244 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৮ কোটি বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "গ্রহ 'Pluto'" },
  },
  95: {
    radii: { atomic: 244, covalent: 180, ionic: 100, vanDerWaals: null },
    ionizationEnergies: { first: 578, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "ডাবল হেক্সাগোনাল ক্লোজ-প্যাকড",
    hardnessMohs: null,
    heatOfFusion: 14.39,
    heatOfVaporization: 238.5,
    molarVolume: 17.63,
    notableIsotopes: [{ symbol: "Am-243 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৭,৩৭০ বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "মহাদেশ 'America'" },
  },
  96: {
    radii: { atomic: 245, covalent: 169, ionic: 97, vanDerWaals: null },
    ionizationEnergies: { first: 581, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "ডাবল হেক্সাগোনাল ক্লোজ-প্যাকড",
    hardnessMohs: null,
    heatOfFusion: null,
    heatOfVaporization: null,
    molarVolume: 18.28,
    notableIsotopes: [{ symbol: "Cm-247 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১৫৬ লক্ষ বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "মেরি ও পিয়ের 'Curie' এর নামে" },
  },
  97: {
    radii: { atomic: 244, covalent: 168, ionic: 96, vanDerWaals: null },
    ionizationEnergies: { first: 601, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড",
    hardnessMohs: null,
    heatOfFusion: null,
    heatOfVaporization: null,
    molarVolume: 16.84,
    notableIsotopes: [{ symbol: "Bk-247 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১৪০০ বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "শহর 'Berkeley'" },
  },
  98: {
    radii: { atomic: 245, covalent: 168, ionic: 95, vanDerWaals: null },
    ionizationEnergies: { first: 608, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "হেক্সাগোনাল ক্লোজ-প্যাকড",
    hardnessMohs: null,
    heatOfFusion: null,
    heatOfVaporization: null,
    molarVolume: 16.5,
    notableIsotopes: [{ symbol: "Cf-251 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৯০০ বছর" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "অঙ্গরাজ্য 'California'" },
  },
  99: {
    radii: { atomic: 245, covalent: 165, ionic: 92, vanDerWaals: null },
    ionizationEnergies: { first: 619, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা (অত্যন্ত অল্প পরিমাণে পাওয়া যায়)",
    hardnessMohs: null,
    heatOfFusion: null,
    heatOfVaporization: null,
    molarVolume: null,
    notableIsotopes: [{ symbol: "Es-252 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৪৭২ দিন" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Albert Einstein' এর নামে" },
  },
  100: {
    radii: { atomic: 245, covalent: 167, ionic: 90, vanDerWaals: null },
    ionizationEnergies: { first: 627, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা (অত্যন্ত অল্প পরিমাণে পাওয়া যায়)",
    hardnessMohs: null,
    heatOfFusion: null,
    heatOfVaporization: null,
    molarVolume: null,
    notableIsotopes: [{ symbol: "Fm-257 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১০০.৫ দিন" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Enrico Fermi' এর নামে" },
  },

  // ── Superheavy synthetic elements (101–118) ──
  101: {
    radii: { atomic: 245, covalent: 173, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 635, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Md-258 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৫১.৫ দিন" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Dmitri Mendeleev' এর নামে" },
  },
  102: {
    radii: { atomic: 245, covalent: 176, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 642, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "No-259 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "৫৮ মিনিট" }],
    discovery: { place: "রাশিয়া", nameOrigin: "বিজ্ঞানী 'Alfred Nobel' এর নামে" },
  },
  103: {
    radii: { atomic: 246, covalent: 161, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 470, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Lr-266 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "১১ ঘণ্টা" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Ernest Lawrence' এর নামে" },
  },
  104: {
    radii: { atomic: null, covalent: 157, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 580, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা (অনুমান: হেক্সাগোনাল ক্লোজ-প্যাকড)",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Rf-267 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~১.৩ ঘণ্টা" }],
    discovery: { place: "রাশিয়া/যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Ernest Rutherford' এর নামে" },
  },
  105: {
    radii: { atomic: null, covalent: 149, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 665, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Db-268 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~২৯ ঘণ্টা" }],
    discovery: { place: "রাশিয়া/যুক্তরাষ্ট্র", nameOrigin: "রাশিয়ার শহর 'Dubna'" },
  },
  106: {
    radii: { atomic: null, covalent: 143, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 757, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Sg-269 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~১৪ মিনিট" }],
    discovery: { place: "যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Glenn T. Seaborg' এর নামে" },
  },
  107: {
    radii: { atomic: null, covalent: 141, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 740, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Bh-270 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~৬১ সেকেন্ড" }],
    discovery: { place: "জার্মানি", nameOrigin: "বিজ্ঞানী 'Niels Bohr' এর নামে" },
  },
  108: {
    radii: { atomic: null, covalent: 134, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 730, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Hs-269 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~১৪ সেকেন্ড" }],
    discovery: { place: "জার্মানি", nameOrigin: "জার্মান রাজ্য 'Hesse' এর ল্যাটিন নাম 'Hassia'" },
  },
  109: {
    radii: { atomic: null, covalent: 129, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 800, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Mt-278 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~৪.৫ সেকেন্ড" }],
    discovery: { place: "জার্মানি", nameOrigin: "বিজ্ঞানী 'Lise Meitner' এর নামে" },
  },
  110: {
    radii: { atomic: null, covalent: 128, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 960, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Ds-281 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~১২.৭ সেকেন্ড" }],
    discovery: { place: "জার্মানি", nameOrigin: "জার্মান শহর 'Darmstadt'" },
  },
  111: {
    radii: { atomic: null, covalent: 121, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 1020, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Rg-282 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~২ মিনিট" }],
    discovery: { place: "জার্মানি", nameOrigin: "বিজ্ঞানী 'Wilhelm Röntgen' এর নামে" },
  },
  112: {
    radii: { atomic: null, covalent: 122, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 1155, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা (অনুমান: তরল/গ্যাস, ঘরের তাপমাত্রায়)",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Cn-285 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~২৯ সেকেন্ড" }],
    discovery: { place: "জার্মানি", nameOrigin: "বিজ্ঞানী 'Nicolaus Copernicus' এর নামে" },
  },
  113: {
    radii: { atomic: null, covalent: 136, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 707, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Nh-286 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~১০ সেকেন্ড" }],
    discovery: { place: "জাপান", nameOrigin: "জাপানের নাম 'Nihon' থেকে — এশিয়ায় আবিষ্কৃত প্রথম মৌল" },
  },
  114: {
    radii: { atomic: null, covalent: 143, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 832, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা (অনুমান: তরল/গ্যাস)",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Fl-289 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~২.৬ সেকেন্ড" }],
    discovery: { place: "রাশিয়া", nameOrigin: "পদার্থবিজ্ঞানী 'Georgy Flyorov' এর নামে" },
  },
  115: {
    radii: { atomic: null, covalent: 162, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 538, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Mc-290 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~৬৫ মিলিসেকেন্ড" }],
    discovery: { place: "রাশিয়া", nameOrigin: "রাশিয়ার 'Moscow' অঞ্চল" },
  },
  116: {
    radii: { atomic: null, covalent: 175, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 663, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Lv-293 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~৬০ মিলিসেকেন্ড" }],
    discovery: { place: "রাশিয়া/যুক্তরাষ্ট্র", nameOrigin: "যুক্তরাষ্ট্রের 'Lawrence Livermore National Laboratory'" },
  },
  117: {
    radii: { atomic: null, covalent: 165, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 736, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Ts-294 (সবচেয়ে স্থিতিশীল)", type: "radioactive", halfLife: "~৫১ মিলিসেকেন্ড" }],
    discovery: { place: "রাশিয়া/যুক্তরাষ্ট্র", nameOrigin: "যুক্তরাষ্ট্রের অঙ্গরাজ্য 'Tennessee'" },
  },
  118: {
    radii: { atomic: null, covalent: 157, ionic: null, vanDerWaals: null },
    ionizationEnergies: { first: 839, second: null, third: null },
    electronAffinity: null,
    crystalStructure: "অজানা (অনুমান: কঠিন, নোবেল গ্যাস হলেও)",
    hardnessMohs: null, heatOfFusion: null, heatOfVaporization: null, molarVolume: null,
    notableIsotopes: [{ symbol: "Og-294 (একমাত্র জ্ঞাত আইসোটোপ)", type: "radioactive", halfLife: "~০.৭ মিলিসেকেন্ড" }],
    discovery: { place: "রাশিয়া/যুক্তরাষ্ট্র", nameOrigin: "বিজ্ঞানী 'Yuri Oganessian' এর নামে" },
  },
};
