// lib/seedData/biochemistry/5-11-karbohaidret-rsayn-jiibrsayn.ts
//
// অধ্যায় 5.11 — কার্বোহাইড্রেট রসায়ন (জীবরসায়ন) (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter511: SeedChapter = {
  code: "5.11",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "কার্বোহাইড্রেট রসায়ন (জীবরসায়ন)",
  chapterOrder: 110,
  topics: [
    {
      title: "কার্বোহাইড্রেটের পরিচিতি (জীবরসায়ন)",
      slug: "karbohaidreter-prichiti-jiibrsayn",
      summary: "",
      subtopics: [
        {
          title: "Definition of carbohydrates",
          slug: "definition-of-carbohydrates",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Classification of carbohydrates",
          slug: "classification-of-carbohydrates",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biological importance (কার্বোহাইড্রেট)",
          slug: "biological-importance-karbohaidret",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Monosaccharides",
      slug: "monosaccharides",
      summary: "",
      subtopics: [
        {
          title: "Structure of monosaccharides",
          slug: "structure-of-monosaccharides",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Aldose",
          slug: "aldose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ketose",
          slug: "ketose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Trioses",
          slug: "trioses",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pentoses",
          slug: "pentoses",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hexoses",
          slug: "hexoses",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "গুরুত্বপূর্ণ Monosaccharides ও Stereochemistry",
      slug: "gurutbpuurn-monosaccharides-o-stereochemistry",
      summary: "",
      subtopics: [
        {
          title: "Glucose (জীবরসায়ন)",
          slug: "glucose-jiibrsayn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fructose (জীবরসায়ন)",
          slug: "fructose-jiibrsayn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Galactose",
          slug: "galactose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ribose (জীবরসায়ন)",
          slug: "ribose-jiibrsayn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Deoxyribose",
          slug: "deoxyribose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "D and L configuration",
          slug: "d-and-l-configuration",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Epimers",
          slug: "epimers",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Anomers",
          slug: "anomers",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Alpha and beta forms",
          slug: "alpha-and-beta-forms",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Disaccharides ও Polysaccharides",
      slug: "disaccharides-o-polysaccharides",
      summary: "",
      subtopics: [
        {
          title: "Maltose",
          slug: "maltose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lactose",
          slug: "lactose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Sucrose",
          slug: "sucrose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glycosidic bond",
          slug: "glycosidic-bond",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Starch",
          slug: "starch-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glycogen",
          slug: "glycogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cellulose",
          slug: "cellulose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chitin",
          slug: "chitin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hyaluronic acid",
          slug: "hyaluronic-acid",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Carbohydrate Metabolism এর ভূমিকা",
      slug: "carbohydrate-metabolism-er-bhuumika",
      summary: "",
      subtopics: [
        {
          title: "Energy source",
          slug: "energy-source",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Storage carbohydrate",
          slug: "storage-carbohydrate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Structural carbohydrate",
          slug: "structural-carbohydrate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter511;
