// lib/seedData/biochemistry/5-17-lipid-bipak.ts
//
// অধ্যায় 5.17 — লিপিড বিপাক (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter517: SeedChapter = {
  code: "5.17",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "লিপিড বিপাক",
  chapterOrder: 170,
  topics: [
    {
      title: "Lipid Digestion ও Absorption",
      slug: "lipid-digestion-o-absorption",
      summary: "",
      subtopics: [
        {
          title: "Dietary fat digestion",
          slug: "dietary-fat-digestion",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bile salt function",
          slug: "bile-salt-function",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Micelle formation",
          slug: "micelle-formation-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fat absorption",
          slug: "fat-absorption",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Fatty Acid Metabolism",
      slug: "fatty-acid-metabolism",
      summary: "",
      subtopics: [
        {
          title: "Acetyl-CoA source",
          slug: "acetyl-coa-source",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fatty acid synthase",
          slug: "fatty-acid-synthase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Malonyl-CoA pathway",
          slug: "malonyl-coa-pathway",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "NADPH requirement",
          slug: "nadph-requirement",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Beta oxidation",
          slug: "beta-oxidation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mitochondrial transport (Fatty Acid)",
          slug: "mitochondrial-transport-fatty-acid",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Acetyl-CoA production",
          slug: "acetyl-coa-production",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Energy yield",
          slug: "energy-yield",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Ketone Body ও Cholesterol Metabolism",
      slug: "ketone-body-o-cholesterol-metabolism",
      summary: "",
      subtopics: [
        {
          title: "Ketone body formation",
          slug: "ketone-body-formation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ketogenesis",
          slug: "ketogenesis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ketolysis",
          slug: "ketolysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ketosis",
          slug: "ketosis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cholesterol synthesis",
          slug: "cholesterol-synthesis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "HMG-CoA reductase",
          slug: "hmg-coa-reductase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cholesterol transport",
          slug: "cholesterol-transport",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cholesterol degradation",
          slug: "cholesterol-degradation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Lipoprotein Metabolism ও Disorders",
      slug: "lipoprotein-metabolism-o-disorders",
      summary: "",
      subtopics: [
        {
          title: "Chylomicron metabolism",
          slug: "chylomicron-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "VLDL metabolism",
          slug: "vldl-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "LDL metabolism",
          slug: "ldl-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "HDL metabolism",
          slug: "hdl-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hyperlipidemia",
          slug: "hyperlipidemia",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Atherosclerosis (লিপিড বিপাক)",
          slug: "atherosclerosis-lipid-bipak",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fatty liver disease",
          slug: "fatty-liver-disease",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Obesity metabolism",
          slug: "obesity-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter517;
