// lib/seedData/biochemistry/5-23-unnt-enjaimbidya.ts
//
// অধ্যায় 5.23 — উন্নত এনজাইমবিদ্যা (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter523: SeedChapter = {
  code: "5.23",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "উন্নত এনজাইমবিদ্যা",
  chapterOrder: 230,
  topics: [
    {
      title: "Enzyme Structure and Function (উন্নত)",
      slug: "enzyme-structure-and-function-unnt",
      summary: "",
      subtopics: [
        {
          title: "Enzyme এর ত্রিমাত্রিক গঠন",
          slug: "enzyme-er-trimatrik-gthn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Active site architecture",
          slug: "active-site-architecture",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Substrate binding mechanism",
          slug: "substrate-binding-mechanism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Enzyme specificity",
          slug: "enzyme-specificity",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Catalytic efficiency",
          slug: "catalytic-efficiency",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Enzyme Catalysis Mechanism",
      slug: "enzyme-catalysis-mechanism",
      summary: "",
      subtopics: [
        {
          title: "Acid-base catalysis",
          slug: "acid-base-catalysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Covalent catalysis",
          slug: "covalent-catalysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Metal ion catalysis",
          slug: "metal-ion-catalysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrostatic catalysis",
          slug: "electrostatic-catalysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Proximity and orientation effects",
          slug: "proximity-and-orientation-effects",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Enzyme Kinetics Advanced",
      slug: "enzyme-kinetics-advanced",
      summary: "",
      subtopics: [
        {
          title: "Michaelis-Menten kinetics (উন্নত)",
          slug: "michaelis-menten-kinetics-unnt",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lineweaver-Burk plot",
          slug: "lineweaver-burk-plot",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Eadie-Hofstee plot",
          slug: "eadie-hofstee-plot",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hanes-Woolf plot",
          slug: "hanes-woolf-plot",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Km এবং Vmax এর ব্যাখ্যা",
          slug: "km-ebng-vmax-er-byakhya",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Turnover number (Kcat)",
          slug: "turnover-number-kcat",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Catalytic efficiency (Kinetics)",
          slug: "catalytic-efficiency-kinetics",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Enzyme Inhibition ও Allosteric Enzymes",
      slug: "enzyme-inhibition-o-allosteric-enzymes",
      summary: "",
      subtopics: [
        {
          title: "Reversible inhibition",
          slug: "reversible-inhibition",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Competitive inhibition (উন্নত)",
          slug: "competitive-inhibition-unnt",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Non-competitive inhibition (উন্নত)",
          slug: "non-competitive-inhibition-unnt",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Uncompetitive inhibition",
          slug: "uncompetitive-inhibition",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mixed inhibition",
          slug: "mixed-inhibition",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Irreversible inhibition",
          slug: "irreversible-inhibition",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Suicide inhibition",
          slug: "suicide-inhibition",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Allosteric regulation (উন্নত)",
          slug: "allosteric-regulation-unnt",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cooperativity",
          slug: "cooperativity",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Positive regulation",
          slug: "positive-regulation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Negative regulation",
          slug: "negative-regulation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Enzyme Regulation, Immobilization ও Engineering",
      slug: "enzyme-regulation-immobilization-o-engineering",
      summary: "",
      subtopics: [
        {
          title: "Covalent modification",
          slug: "covalent-modification",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Phosphorylation",
          slug: "phosphorylation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Proteolytic activation",
          slug: "proteolytic-activation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Zymogen activation",
          slug: "zymogen-activation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Immobilized enzymes",
          slug: "immobilized-enzymes",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Industrial applications (এনজাইম)",
          slug: "industrial-applications-enjaim",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biosensors (এনজাইম)",
          slug: "biosensors-enjaim",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biocatalysis",
          slug: "biocatalysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Directed evolution",
          slug: "directed-evolution",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Protein engineering (এনজাইম)",
          slug: "protein-engineering-enjaim",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Enzyme optimization",
          slug: "enzyme-optimization",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter523;
