// lib/seedData/biochemistry/5-25-kyansar-jiibrsayn.ts
//
// অধ্যায় 5.25 — ক্যান্সার জীবরসায়ন (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter525: SeedChapter = {
  code: "5.25",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "ক্যান্সার জীবরসায়ন",
  chapterOrder: 250,
  topics: [
    {
      title: "Cancer Biology ও Molecular Basis",
      slug: "cancer-biology-o-molecular-basis",
      summary: "",
      subtopics: [
        {
          title: "Cancer এর ধারণা",
          slug: "cancer-er-dharna",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Normal cell বনাম cancer cell",
          slug: "normal-cell-bnam-cancer-cell",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Tumor formation",
          slug: "tumor-formation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Oncogene",
          slug: "oncogene",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Tumor suppressor gene",
          slug: "tumor-suppressor-gene",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Proto-oncogene",
          slug: "proto-oncogene",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Genetic mutation (ক্যান্সার)",
          slug: "genetic-mutation-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Cell Cycle Regulation ও Apoptosis",
      slug: "cell-cycle-regulation-o-apoptosis",
      summary: "",
      subtopics: [
        {
          title: "Cell cycle phases",
          slug: "cell-cycle-phases",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cyclins",
          slug: "cyclins",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cyclin-dependent kinases",
          slug: "cyclin-dependent-kinases",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cell cycle checkpoints",
          slug: "cell-cycle-checkpoints",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Programmed cell death",
          slug: "programmed-cell-death",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Apoptotic pathways",
          slug: "apoptotic-pathways",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Caspases",
          slug: "caspases",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Anti-apoptotic proteins",
          slug: "anti-apoptotic-proteins",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Cancer Metabolism ও Signaling Pathways",
      slug: "cancer-metabolism-o-signaling-pathways",
      summary: "",
      subtopics: [
        {
          title: "Warburg effect",
          slug: "warburg-effect",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Altered glucose metabolism",
          slug: "altered-glucose-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lipid metabolism in cancer",
          slug: "lipid-metabolism-in-cancer",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Amino acid metabolism (ক্যান্সার)",
          slug: "amino-acid-metabolism-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "MAPK pathway",
          slug: "mapk-pathway",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "PI3K-AKT pathway",
          slug: "pi3k-akt-pathway",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Wnt signaling",
          slug: "wnt-signaling",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Notch signaling",
          slug: "notch-signaling",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Cancer Diagnosis ও Therapy",
      slug: "cancer-diagnosis-o-therapy",
      summary: "",
      subtopics: [
        {
          title: "Tumor biomarkers (ক্যান্সার)",
          slug: "tumor-biomarkers-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular diagnosis (ক্যান্সার)",
          slug: "molecular-diagnosis-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Liquid biopsy",
          slug: "liquid-biopsy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chemotherapy mechanism",
          slug: "chemotherapy-mechanism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Targeted therapy (ক্যান্সার)",
          slug: "targeted-therapy-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Immunotherapy (ক্যান্সার)",
          slug: "immunotherapy-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Gene therapy (ক্যান্সার)",
          slug: "gene-therapy-kyansar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter525;
