// lib/seedData/biochemistry/5-5-karbohaidret-bipak.ts
//
// অধ্যায় 5.5 — কার্বোহাইড্রেট বিপাক (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter55: SeedChapter = {
  code: "5.5",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "কার্বোহাইড্রেট বিপাক",
  chapterOrder: 50,
  topics: [
    {
      title: "Glycolysis ও Regulation",
      slug: "glycolysis-o-regulation",
      summary: "",
      subtopics: [
        {
          title: "Glycolysis এর পরিচিতি",
          slug: "glycolysis-er-prichiti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cytoplasmic glucose breakdown",
          slug: "cytoplasmic-glucose-breakdown",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Preparatory phase",
          slug: "preparatory-phase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Payoff phase",
          slug: "payoff-phase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ATP production (Glycolysis)",
          slug: "atp-production-glycolysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "NADH production (Glycolysis)",
          slug: "nadh-production-glycolysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hexokinase",
          slug: "hexokinase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glucokinase",
          slug: "glucokinase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Phosphofructokinase",
          slug: "phosphofructokinase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pyruvate kinase",
          slug: "pyruvate-kinase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Anaerobic Respiration ও Pyruvate Metabolism",
      slug: "anaerobic-respiration-o-pyruvate-metabolism",
      summary: "",
      subtopics: [
        {
          title: "Lactate formation",
          slug: "lactate-formation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fermentation (কার্বোহাইড্রেট বিপাক)",
          slug: "fermentation-karbohaidret-bipak",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Muscle fatigue",
          slug: "muscle-fatigue",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pyruvate oxidation",
          slug: "pyruvate-oxidation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Acetyl-CoA formation",
          slug: "acetyl-coa-formation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pyruvate dehydrogenase complex",
          slug: "pyruvate-dehydrogenase-complex",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Citric Acid Cycle (Krebs Cycle)",
      slug: "citric-acid-cycle-krebs-cycle",
      summary: "",
      subtopics: [
        {
          title: "Cycle overview",
          slug: "cycle-overview",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mitochondrial location",
          slug: "mitochondrial-location",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Steps of Krebs cycle",
          slug: "steps-of-krebs-cycle",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ATP/GTP production",
          slug: "atp-gtp-production",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "NADH and FADH₂ production",
          slug: "nadh-and-fadh-production",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Gluconeogenesis, Glycogenesis ও Glycogenolysis",
      slug: "gluconeogenesis-glycogenesis-o-glycogenolysis",
      summary: "",
      subtopics: [
        {
          title: "Glucose synthesis",
          slug: "glucose-synthesis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Non-carbohydrate precursors",
          slug: "non-carbohydrate-precursors",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lactate cycle",
          slug: "lactate-cycle",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Regulation (Gluconeogenesis)",
          slug: "regulation-gluconeogenesis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glycogen synthesis",
          slug: "glycogen-synthesis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glycogen synthase",
          slug: "glycogen-synthase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Branching enzyme",
          slug: "branching-enzyme",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glycogen breakdown",
          slug: "glycogen-breakdown",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glycogen phosphorylase",
          slug: "glycogen-phosphorylase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hormonal regulation (Glycogenolysis)",
          slug: "hormonal-regulation-glycogenolysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Pentose Phosphate Pathway ও Blood Glucose Regulation",
      slug: "pentose-phosphate-pathway-o-blood-glucose-regulation",
      summary: "",
      subtopics: [
        {
          title: "Oxidative phase",
          slug: "oxidative-phase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Non-oxidative phase",
          slug: "non-oxidative-phase",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "NADPH production (Pentose)",
          slug: "nadph-production-pentose",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ribose synthesis",
          slug: "ribose-synthesis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Insulin action",
          slug: "insulin-action",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glucagon action",
          slug: "glucagon-action",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Diabetes mellitus (কার্বোহাইড্রেট বিপাক)",
          slug: "diabetes-mellitus-karbohaidret-bipak",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hypoglycemia",
          slug: "hypoglycemia",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hyperglycemia",
          slug: "hyperglycemia",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter55;
