// lib/seedData/biochemistry/5-73-unnt-klinikyal-jiibrsayn.ts
//
// অধ্যায় 5.73 — উন্নত ক্লিনিক্যাল জীবরসায়ন (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter573: SeedChapter = {
  code: "5.73",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "উন্নত ক্লিনিক্যাল জীবরসায়ন",
  chapterOrder: 730,
  topics: [
    {
      title: "Clinical Biochemistry এর ভিত্তি ও Blood Advanced",
      slug: "clinical-biochemistry-er-bhitti-o-blood-advanced",
      summary: "",
      subtopics: [
        {
          title: "রোগ নির্ণয়ে জীবরসায়নের ভূমিকা",
          slug: "rog-nirnye-jiibrsayner-bhuumika",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Laboratory medicine",
          slug: "laboratory-medicine",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Diagnostic biomarkers (উন্নত ক্লিনিক্যাল)",
          slug: "diagnostic-biomarkers-unnt-klinikyal",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Reference range ও interpretation",
          slug: "reference-range-o-interpretation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Plasma proteins analysis",
          slug: "plasma-proteins-analysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Albumin ও globulin",
          slug: "albumin-o-globulin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Acute phase proteins",
          slug: "acute-phase-proteins",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Blood electrolyte analysis",
          slug: "blood-electrolyte-analysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Liver ও Kidney Disease Biochemistry",
      slug: "liver-o-kidney-disease-biochemistry",
      summary: "",
      subtopics: [
        {
          title: "Hepatic metabolism",
          slug: "hepatic-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bilirubin metabolism",
          slug: "bilirubin-metabolism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Liver function markers",
          slug: "liver-function-markers",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ALT, AST, ALP, GGT analysis",
          slug: "alt-ast-alp-ggt-analysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hepatitis biomarkers",
          slug: "hepatitis-biomarkers",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Renal filtration chemistry",
          slug: "renal-filtration-chemistry",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Creatinine clearance",
          slug: "creatinine-clearance",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Urea metabolism (উন্নত ক্লিনিক্যাল)",
          slug: "urea-metabolism-unnt-klinikyal",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrolyte imbalance",
          slug: "electrolyte-imbalance",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chronic kidney disease markers",
          slug: "chronic-kidney-disease-markers",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Cardiovascular ও Endocrine Clinical Biochemistry",
      slug: "cardiovascular-o-endocrine-clinical-biochemistry",
      summary: "",
      subtopics: [
        {
          title: "Cardiac biomarkers (উন্নত ক্লিনিক্যাল)",
          slug: "cardiac-biomarkers-unnt-klinikyal",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Troponin analysis",
          slug: "troponin-analysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "CK-MB",
          slug: "ck-mb",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lipid profile (উন্নত ক্লিনিক্যাল)",
          slug: "lipid-profile-unnt-klinikyal",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Atherosclerosis mechanism",
          slug: "atherosclerosis-mechanism",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Thyroid hormones analysis",
          slug: "thyroid-hormones-analysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Insulin measurement",
          slug: "insulin-measurement",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cortisol testing",
          slug: "cortisol-testing",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Growth hormone analysis",
          slug: "growth-hormone-analysis",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Cancer Biomarkers",
      slug: "cancer-biomarkers",
      summary: "",
      subtopics: [
        {
          title: "Tumor markers",
          slug: "tumor-markers",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "PSA",
          slug: "psa",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "CA-125",
          slug: "ca-125",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "CEA",
          slug: "cea",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular cancer diagnosis (উন্নত ক্লিনিক্যাল)",
          slug: "molecular-cancer-diagnosis-unnt-klinikyal",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter573;
