// lib/seedData/biochemistry/5-82-jiibrsayne-puurnangg-gbeshna-rodmyap.ts
//
// অধ্যায় 5.82 — জীবরসায়নে পূর্ণাঙ্গ গবেষণা রোডম্যাপ (Biochemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter582: SeedChapter = {
  code: "5.82",
  category: "biochemistry",
  structure: "3-level",
  chapterTitle: "জীবরসায়নে পূর্ণাঙ্গ গবেষণা রোডম্যাপ",
  chapterOrder: 820,
  topics: [
    {
      title: "Basic ও Advanced Laboratory Skills",
      slug: "basic-o-advanced-laboratory-skills",
      summary: "",
      subtopics: [
        {
          title: "Scientific thinking",
          slug: "scientific-thinking",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Experimental design (গবেষণা রোডম্যাপ)",
          slug: "experimental-design-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Laboratory techniques (গবেষণা রোডম্যাপ)",
          slug: "laboratory-techniques-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular biology techniques (গবেষণা রোডম্যাপ)",
          slug: "molecular-biology-techniques-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Protein analysis (গবেষণা রোডম্যাপ)",
          slug: "protein-analysis-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cell culture (গবেষণা রোডম্যাপ)",
          slug: "cell-culture-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bioanalytical methods (গবেষণা রোডম্যাপ)",
          slug: "bioanalytical-methods-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Data Science ও Research Fields Selection",
      slug: "data-science-o-research-fields-selection",
      summary: "",
      subtopics: [
        {
          title: "Bioinformatics (গবেষণা রোডম্যাপ)",
          slug: "bioinformatics-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Programming basics",
          slug: "programming-basics",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biological data analysis (গবেষণা রোডম্যাপ)",
          slug: "biological-data-analysis-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "AI applications (গবেষণা রোডম্যাপ)",
          slug: "ai-applications-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cancer research",
          slug: "cancer-research",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Drug discovery (গবেষণা রোডম্যাপ)",
          slug: "drug-discovery-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Genetics (গবেষণা রোডম্যাপ)",
          slug: "genetics-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biotechnology (গবেষণা রোডম্যাপ)",
          slug: "biotechnology-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Neuroscience",
          slug: "neuroscience",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Immunology (গবেষণা রোডম্যাপ)",
          slug: "immunology-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Scientific Publication ও Career Paths",
      slug: "scientific-publication-o-career-paths",
      summary: "",
      subtopics: [
        {
          title: "Research paper writing (গবেষণা রোডম্যাপ)",
          slug: "research-paper-writing-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Literature review (গবেষণা রোডম্যাপ)",
          slug: "literature-review-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Scientific communication (গবেষণা রোডম্যাপ)",
          slug: "scientific-communication-gbeshna-rodmyap",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Peer review process",
          slug: "peer-review-process",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biochemist",
          slug: "biochemist",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular biologist",
          slug: "molecular-biologist",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Clinical researcher",
          slug: "clinical-researcher",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biotechnology scientist",
          slug: "biotechnology-scientist",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pharmaceutical researcher",
          slug: "pharmaceutical-researcher",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bioinformatics scientist",
          slug: "bioinformatics-scientist",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biomedical scientist",
          slug: "biomedical-scientist",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter582;
