// lib/seedData/inorganic/3-1-atomic-structure.ts
//
// অধ্যায় 3.1 — পরমাণুর গঠন (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter31: SeedChapter = {
  code: "3.1",
  category: "inorganic-chemistry",
  chapterTitle: "পরমাণুর গঠন",
  chapterOrder: 10,
  topics: [
    {
      title: "পদার্থের মৌলিক কণা",
      slug: "pdarther-moulik-kna",
      summary: "",
      subtopics: [
        {
          title: "ইলেকট্রন, প্রোটন, নিউট্রন",
          slug: "ilektrn-protn-niutrn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পারমাণবিক সংখ্যা",
          slug: "parmanbik-sngkhya-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ভর সংখ্যা",
          slug: "bhr-sngkhya-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আইসোটোপ",
          slug: "aaisotop-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আইসোবার",
          slug: "aaisobar-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আইসোটোন",
          slug: "aaisoton-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আইসোমার (নিউক্লিয়ার)",
          slug: "aaisomar-niukliyar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "তেজস্ক্রিয়তা",
          slug: "tejskriyta-3",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "তেজস্ক্রিয় ক্ষয়",
          slug: "tejskriy-kshy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অর্ধায়ু",
          slug: "ardhayu-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "পরমাণুর বিভিন্ন মডেল",
      slug: "prmanur-bibhinn-mdel",
      summary: "",
      subtopics: [
        {
          title: "ডাল্টনের তত্ত্ব",
          slug: "daltner-tttb",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "থমসনের মডেল",
          slug: "thmsner-mdel-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "রাদারফোর্ড মডেল",
          slug: "radarphord-mdel",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "বোর মডেল",
          slug: "bor-mdel-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আধুনিক কোয়ান্টাম মডেল",
          slug: "aadhunik-koyantam-mdel",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "তরঙ্গ-কণা দ্বৈত ধর্ম",
          slug: "trngg-kna-dboit-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ডি-ব্রগলি সমীকরণ",
          slug: "di-brgli-smiikrn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "হাইজেনবার্গের অনিশ্চয়তা নীতি",
          slug: "haijenbarger-anishchyta-niiti-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "শ্রোডিঙ্গারের সমীকরণ",
          slug: "shrodinggarer-smiikrn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "অরবিট ও অরবিটাল",
      slug: "arbit-o-arbital",
      summary: "",
      subtopics: [
        {
          title: "কোয়ান্টাম সংখ্যা",
          slug: "koyantam-sngkhya-3",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "s, p, d, f অরবিটাল",
          slug: "s-p-d-f-arbital-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আউফবাউ নীতি",
          slug: "aauphbau-niiti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পাউলির বর্জন নীতি",
          slug: "paulir-brjn-niiti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "হুন্ডের নীতি",
          slug: "hunder-niiti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ইলেকট্রন বিন্যাস",
          slug: "ilektrn-binyas-3",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ব্যতিক্রমী ইলেকট্রন বিন্যাস",
          slug: "bytikrmii-ilektrn-binyas",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter31;
