// lib/seedData/inorganic/3-10-metallurgy.ts
//
// অধ্যায় 3.10 — ধাতুবিদ্যা (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter310: SeedChapter = {
  code: "3.10",
  category: "inorganic-chemistry",
  chapterTitle: "ধাতুবিদ্যা",
  chapterOrder: 100,
  topics: [
    {
      title: "ধাতু নিষ্কাশনের মূল ধারণা",
      slug: "dhatu-nishkashner-muul-dharna",
      summary: "",
      subtopics: [
        {
          title: "আকরিক (Ore)",
          slug: "aakrik-ore",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "খনিজ (Mineral)",
          slug: "khnij-mineral",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গ্যাং (Gangue)",
          slug: "gyang-gangue",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ধাতুর সক্রিয়তা",
          slug: "dhatur-skriyta",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ধাতুর শ্রেণিবিন্যাস",
          slug: "dhatur-shrenibinyas",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "আকরিক প্রস্তুতি",
      slug: "aakrik-prstuti",
      summary: "",
      subtopics: [
        {
          title: "চূর্ণন (Crushing)",
          slug: "chuurnn-crushing",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গুঁড়ো করা (Grinding)",
          slug: "gudo-kra-grinding",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Concentration of Ore",
          slug: "concentration-of-ore",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hydraulic Washing",
          slug: "hydraulic-washing",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Magnetic Separation",
          slug: "magnetic-separation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Froth Floatation",
          slug: "froth-floatation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Leaching",
          slug: "leaching",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "ধাতু নিষ্কাশন পদ্ধতি",
      slug: "dhatu-nishkashn-pddhti",
      summary: "",
      subtopics: [
        {
          title: "Calcination",
          slug: "calcination",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Roasting",
          slug: "roasting",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Reduction",
          slug: "reduction",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Smelting",
          slug: "smelting",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrolytic Reduction",
          slug: "electrolytic-reduction",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "বিভিন্ন ধাতু নিষ্কাশন",
      slug: "bibhinn-dhatu-nishkashn",
      summary: "",
      subtopics: [
        {
          title: "সোডিয়াম নিষ্কাশন",
          slug: "sodiyam-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পটাশিয়াম নিষ্কাশন",
          slug: "ptashiyam-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ম্যাগনেসিয়াম নিষ্কাশন",
          slug: "myagnesiyam-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অ্যালুমিনিয়াম নিষ্কাশন",
          slug: "ayaluminiyam-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "লোহা নিষ্কাশন",
          slug: "loha-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "তামা নিষ্কাশন",
          slug: "tama-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "দস্তা নিষ্কাশন",
          slug: "dsta-nishkashn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "পরিশোধন পদ্ধতি",
      slug: "prishodhn-pddhti",
      summary: "",
      subtopics: [
        {
          title: "Electrolytic Refining",
          slug: "electrolytic-refining",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Zone Refining",
          slug: "zone-refining",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Vapour Phase Refining",
          slug: "vapour-phase-refining",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Distillation",
          slug: "distillation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "মিশ্র ধাতু (Alloy)",
      slug: "mishr-dhatu-alloy",
      summary: "",
      subtopics: [
        {
          title: "সংজ্ঞা (Alloy)",
          slug: "sngjnya-alloy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সংকর ধাতু তৈরির কারণ",
          slug: "sngkr-dhatu-toirir-karn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ব্রোঞ্জ",
          slug: "bronyj",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পিতল",
          slug: "pitl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "স্টেইনলেস স্টিল",
          slug: "steinles-stil",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ডুরালুমিন",
          slug: "duralumin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter310;
