// lib/seedData/inorganic/3-16-environmental-chemistry.ts
//
// অধ্যায় 3.16 — পরিবেশ রসায়ন (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter316: SeedChapter = {
  code: "3.16",
  category: "inorganic-chemistry",
  structure: "3-level",
  chapterTitle: "পরিবেশ রসায়ন",
  chapterOrder: 160,
  topics: [
    {
      title: "মৌলিক ধারণা (পরিবেশ)",
      slug: "moulik-dharna-pribesh",
      summary: "",
      subtopics: [
        {
          title: "পরিবেশের উপাদান",
          slug: "pribesher-upadan",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "বায়ুমণ্ডল",
          slug: "bayumndl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "জলমণ্ডল",
          slug: "jlmndl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "স্থলমণ্ডল",
          slug: "sthlmndl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "জীবমণ্ডল",
          slug: "jiibmndl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পরিবেশে রাসায়নিক পদার্থের ভূমিকা",
          slug: "pribeshe-rasaynik-pdarther-bhuumika",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "বায়ু দূষণ",
      slug: "bayu-duushn-2",
      summary: "",
      subtopics: [
        {
          title: "বায়ু দূষণের উৎস",
          slug: "bayu-duushner-uts",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "প্রাকৃতিক ও মানবসৃষ্ট দূষণ",
          slug: "prakritik-o-manbsrisht-duushn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "CO",
          slug: "co-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "CO₂ (দূষক)",
          slug: "co-duushk",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "SO₂",
          slug: "so",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "NOx",
          slug: "nox",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "O₃ (দূষক)",
          slug: "o-duushk",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ধূলিকণা (Particulate Matter)",
          slug: "dhuulikna-particulate-matter",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "বায়ু দূষণের প্রভাব",
      slug: "bayu-duushner-prbhab",
      summary: "",
      subtopics: [
        {
          title: "গ্রিনহাউস প্রভাব",
          slug: "grinhaus-prbhab-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "বৈশ্বিক উষ্ণায়ন",
          slug: "boishbik-ushnayn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "জলবায়ু পরিবর্তন",
          slug: "jlbayu-pribrtn-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অ্যাসিড বৃষ্টি",
          slug: "ayasid-brishti-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ওজোন স্তর ক্ষয়",
          slug: "ojon-str-kshy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "স্মগ (Smog)",
          slug: "smg-smog",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "পানি ও মাটি দূষণ",
      slug: "pani-o-mati-duushn",
      summary: "",
      subtopics: [
        {
          title: "পানির দূষণের উৎস",
          slug: "panir-duushner-uts",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "শিল্প বর্জ্য",
          slug: "shilp-brjy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কৃষি বর্জ্য",
          slug: "krishi-brjy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ভারী ধাতু দূষণ",
          slug: "bharii-dhatu-duushn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আর্সেনিক দূষণ",
          slug: "aarsenik-duushn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ফ্লোরাইড দূষণ",
          slug: "phloraid-duushn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কীটনাশক দূষণ",
          slug: "kiitnashk-duushn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সার দূষণ",
          slug: "sar-duushn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "বর্জ্য ব্যবস্থাপনা",
          slug: "brjy-bybsthapna",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "পানি বিশুদ্ধকরণ পদ্ধতি",
      slug: "pani-bishuddhkrn-pddhti",
      summary: "",
      subtopics: [
        {
          title: "Filtration",
          slug: "filtration",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Sedimentation",
          slug: "sedimentation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chlorination",
          slug: "chlorination",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ozonation",
          slug: "ozonation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Reverse Osmosis",
          slug: "reverse-osmosis-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter316;
