// lib/seedData/inorganic/3-37-metal-cluster-nanochemistry.ts
//
// অধ্যায় 3.37 — Metal Cluster ও Nanochemistry (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter337: SeedChapter = {
  code: "3.37",
  category: "inorganic-chemistry",
  structure: "3-level",
  chapterTitle: "Metal Cluster ও Nanochemistry",
  chapterOrder: 370,
  topics: [
    {
      title: "Metal Cluster Chemistry",
      slug: "metal-cluster-chemistry",
      summary: "",
      subtopics: [
        {
          title: "Metal Cluster এর সংজ্ঞা",
          slug: "metal-cluster-er-sngjnya",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Metal-Metal Bond (Cluster)",
          slug: "metal-metal-bond-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cluster Electron Counting",
          slug: "cluster-electron-counting",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Low Nuclearity Cluster",
          slug: "low-nuclearity-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "High Nuclearity Cluster",
          slug: "high-nuclearity-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fe Cluster",
          slug: "fe-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Co Cluster",
          slug: "co-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ru Cluster",
          slug: "ru-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Nanomaterial এর ধারণা ও ধরন",
      slug: "nanomaterial-er-dharna-o-dhrn",
      summary: "",
      subtopics: [
        {
          title: "Nanometer Scale",
          slug: "nanometer-scale",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Quantum Effect",
          slug: "quantum-effect",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Surface Area Effect",
          slug: "surface-area-effect",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nanoparticle (Nanochemistry)",
          slug: "nanoparticle-nanochemistry",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nanotube",
          slug: "nanotube",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nanowire",
          slug: "nanowire",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Quantum Dot (Nanochemistry অধ্যায়)",
          slug: "quantum-dot-nanochemistry-adhyay",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Graphene (Nanochemistry)",
          slug: "graphene-nanochemistry",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "প্রস্তুতি পদ্ধতি ও বৈশিষ্ট্য (Nano)",
      slug: "prstuti-pddhti-o-boishishty-nano",
      summary: "",
      subtopics: [
        {
          title: "Top-down Method",
          slug: "top-down-method",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bottom-up Method",
          slug: "bottom-up-method",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Sol-Gel Method",
          slug: "sol-gel-method",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chemical Vapor Deposition",
          slug: "chemical-vapor-deposition",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Optical Property",
          slug: "optical-property",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrical Property (Nano)",
          slug: "electrical-property-nano",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Magnetic Property (Nano)",
          slug: "magnetic-property-nano",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Catalytic Property",
          slug: "catalytic-property",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "ব্যবহার (Cluster ও Nano)",
      slug: "bybhar-cluster-o-nano",
      summary: "",
      subtopics: [
        {
          title: "Catalyst (Cluster)",
          slug: "catalyst-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Material Science",
          slug: "material-science",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electronics (Cluster)",
          slug: "electronics-cluster",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Medicine (Nano)",
          slug: "medicine-nano",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Energy Storage (Nano)",
          slug: "energy-storage-nano",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Environmental Technology",
          slug: "environmental-technology",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter337;
