// lib/seedData/inorganic/3-40-descriptive-chemistry.ts
//
// অধ্যায় 3.40 — Descriptive Chemistry (মৌলভিত্তিক) (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter340: SeedChapter = {
  code: "3.40",
  category: "inorganic-chemistry",
  chapterTitle: "Descriptive Chemistry (মৌলভিত্তিক)",
  chapterOrder: 400,
  topics: [
    {
      title: "Descriptive Chemistry এর ধারণা",
      slug: "descriptive-chemistry-er-dharna",
      summary: "",
      subtopics: [
        {
          title: "মৌলগুলোর স্বতন্ত্র বৈশিষ্ট্য",
          slug: "moulgulor-sbtntr-boishishty",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পর্যায় সারণিতে অবস্থানের প্রভাব",
          slug: "pryay-sarnite-absthaner-prbhab",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "মৌলের প্রস্তুতি, ধর্ম ও ব্যবহার",
          slug: "mouler-prstuti-dhrm-o-bybhar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "হাইড্রোজেন (Descriptive)",
      slug: "haidrojen-descriptive",
      summary: "",
      subtopics: [
        {
          title: "হাইড্রোজেনের অবস্থান (Descriptive)",
          slug: "haidrojener-absthan-descriptive",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "প্রোটিয়াম",
          slug: "protiyam",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ডিউটেরিয়াম",
          slug: "diuteriyam",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ট্রিটিয়াম",
          slug: "tritiyam",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "প্রস্তুতি পদ্ধতি (হাইড্রোজেন, Descriptive)",
          slug: "prstuti-pddhti-haidrojen-descriptive",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "রাসায়নিক ধর্ম (হাইড্রোজেন, Descriptive)",
          slug: "rasaynik-dhrm-haidrojen-descriptive",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "হাইড্রাইড গঠন",
          slug: "haidraid-gthn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hydrogen Bonding (Descriptive)",
          slug: "hydrogen-bonding-descriptive",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "জ্বালানি হিসেবে ব্যবহার",
          slug: "jbalani-hisebe-bybhar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "ক্ষার ধাতু (Descriptive)",
      slug: "kshar-dhatu-descriptive",
      summary: "",
      subtopics: [
        {
          title: "Li",
          slug: "li-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Na (ক্ষার ধাতু)",
          slug: "na-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "K (ক্ষার ধাতু)",
          slug: "k-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Rb",
          slug: "rb",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cs",
          slug: "cs",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ইলেকট্রন বিন্যাস (ক্ষার ধাতু)",
          slug: "ilektrn-binyas-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পারমাণবিক আকার (ক্ষার ধাতু)",
          slug: "parmanbik-aakar-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আয়নীকরণ শক্তি (ক্ষার ধাতু)",
          slug: "aayniikrn-shkti-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "রাসায়নিক সক্রিয়তা",
          slug: "rasaynik-skriyta",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পানির সাথে বিক্রিয়া",
          slug: "panir-sathe-bikriya",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অক্সাইড ও পারঅক্সাইড",
          slug: "aksaid-o-paraksaid",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "হাইড্রোক্সাইড",
          slug: "haidroksaid",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "লবণসমূহ (ক্ষার ধাতু)",
          slug: "lbnsmuuh-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Flame Test (ক্ষার ধাতু)",
          slug: "flame-test-kshar-dhatu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "ক্ষারীয় মৃত্তিকা ধাতু (Descriptive)",
      slug: "kshariiy-mrittika-dhatu-descriptive",
      summary: "",
      subtopics: [
        {
          title: "Be",
          slug: "be",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mg (ক্ষারীয় মৃত্তিকা)",
          slug: "mg-kshariiy-mrittika",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ca (ক্ষারীয় মৃত্তিকা)",
          slug: "ca-kshariiy-mrittika",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Sr",
          slug: "sr",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ba",
          slug: "ba",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Be এর অস্বাভাবিক ধর্ম",
          slug: "be-er-asbabhabik-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mg এর ধর্ম",
          slug: "mg-er-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Calcium এর যৌগ",
          slug: "calcium-er-youg",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Carbonate ও Sulfate",
          slug: "carbonate-o-sulfate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কঠিন পানি (ক্ষারীয় মৃত্তিকা)",
          slug: "kthin-pani-kshariiy-mrittika",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biological Importance (ক্ষারীয় মৃত্তিকা)",
          slug: "biological-importance-kshariiy-mrittika",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter340;
