// lib/seedData/inorganic/3-42-lanthanide-actinide-advanced.ts
//
// অধ্যায় 3.42 — Lanthanide ও Actinide Advanced Chemistry (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter342: SeedChapter = {
  code: "3.42",
  category: "inorganic-chemistry",
  structure: "3-level",
  chapterTitle: "Lanthanide ও Actinide Advanced Chemistry",
  chapterOrder: 420,
  topics: [
    {
      title: "Lanthanides",
      slug: "lanthanides",
      summary: "",
      subtopics: [
        {
          title: "La থেকে Lu",
          slug: "la-theke-lu",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electron Configuration (Lanthanide)",
          slug: "electron-configuration-lanthanide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lanthanide Contraction (Advanced)",
          slug: "lanthanide-contraction-advanced",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Oxidation State (Lanthanide)",
          slug: "oxidation-state-lanthanide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Magnetic Property (Lanthanide)",
          slug: "magnetic-property-lanthanide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Color Formation (Lanthanide)",
          slug: "color-formation-lanthanide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Separation Methods (Lanthanide)",
          slug: "separation-methods-lanthanide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lanthanide Oxide",
          slug: "lanthanide-oxide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Lanthanide Halide",
          slug: "lanthanide-halide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Organolanthanide Compound",
          slug: "organolanthanide-compound",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Permanent Magnet",
          slug: "permanent-magnet",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Laser Material",
          slug: "laser-material",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electronics (Lanthanide)",
          slug: "electronics-lanthanide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Actinides",
      slug: "actinides",
      summary: "",
      subtopics: [
        {
          title: "Ac থেকে Lr",
          slug: "ac-theke-lr",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Radioactivity (Actinide)",
          slug: "radioactivity-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Uranium Chemistry (Actinide)",
          slug: "uranium-chemistry-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Thorium Chemistry (Actinide)",
          slug: "thorium-chemistry-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Plutonium Chemistry (Actinide)",
          slug: "plutonium-chemistry-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nuclear Fuel (Actinide)",
          slug: "nuclear-fuel-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nuclear Energy (Actinide)",
          slug: "nuclear-energy-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nuclear Medicine (Actinide)",
          slug: "nuclear-medicine-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Research (Actinide)",
          slug: "research-actinide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter342;
