// lib/seedData/inorganic/3-49-halogen-chemistry.ts
//
// অধ্যায় 3.49 — Halogen Chemistry (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter349: SeedChapter = {
  code: "3.49",
  category: "inorganic-chemistry",
  chapterTitle: "Halogen Chemistry",
  chapterOrder: 490,
  topics: [
    {
      title: "গ্রুপ-১৭ মৌল ও মৌলিক ধর্ম",
      slug: "grup-17-moul-o-moulik-dhrm",
      summary: "",
      subtopics: [
        {
          title: "Fluorine (F)",
          slug: "fluorine-f",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chlorine (Cl)",
          slug: "chlorine-cl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bromine (Br)",
          slug: "bromine-br",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Iodine (I)",
          slug: "iodine-i",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Astatine (At)",
          slug: "astatine-at",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ইলেকট্রন বিন্যাস (Halogen)",
          slug: "ilektrn-binyas-halogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "পারমাণবিক আকার (Halogen)",
          slug: "parmanbik-aakar-halogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ইলেকট্রোনেগেটিভিটি (Halogen)",
          slug: "ilektronegetibhiti-halogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electron Affinity",
          slug: "electron-affinity",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Oxidizing Power",
          slug: "oxidizing-power",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Fluorine ও Chlorine Chemistry",
      slug: "fluorine-o-chlorine-chemistry",
      summary: "",
      subtopics: [
        {
          title: "Fluorine এর অস্বাভাবিক ধর্ম",
          slug: "fluorine-er-asbabhabik-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "F₂ এর প্রস্তুতি",
          slug: "f-er-prstuti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fluoride Ion",
          slug: "fluoride-ion",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hydrogen Fluoride (HF)",
          slug: "hydrogen-fluoride-hf",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fluorocarbon",
          slug: "fluorocarbon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fluorine এর ব্যবহার",
          slug: "fluorine-er-bybhar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cl₂ প্রস্তুতি",
          slug: "cl-prstuti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chloride Compound",
          slug: "chloride-compound",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "HCl (Halogen)",
          slug: "hcl-halogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chlorine Oxides",
          slug: "chlorine-oxides",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hypochlorite",
          slug: "hypochlorite",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bleaching Powder",
          slug: "bleaching-powder",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Disinfection",
          slug: "disinfection",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Bromine, Iodine ও Halogen যৌগ",
      slug: "bromine-iodine-o-halogen-youg",
      summary: "",
      subtopics: [
        {
          title: "Bromine এর ধর্ম",
          slug: "bromine-er-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Iodine এর ধর্ম",
          slug: "iodine-er-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Iodide Compound",
          slug: "iodide-compound",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Interhalogen Compound (Halogen অধ্যায়)",
          slug: "interhalogen-compound-halogen-adhyay",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Polyhalide Ion",
          slug: "polyhalide-ion",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hydrogen Halide",
          slug: "hydrogen-halide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Metal Halide",
          slug: "metal-halide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Polyhalogen Compound",
          slug: "polyhalogen-compound",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Oxyhalogen Compound",
          slug: "oxyhalogen-compound",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter349;
