// lib/seedData/inorganic/3-51-nitrogen-phosphorus-chemistry.ts
//
// অধ্যায় 3.51 — Nitrogen ও Phosphorus Chemistry (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter351: SeedChapter = {
  code: "3.51",
  category: "inorganic-chemistry",
  chapterTitle: "Nitrogen ও Phosphorus Chemistry",
  chapterOrder: 510,
  topics: [
    {
      title: "Nitrogen Chemistry",
      slug: "nitrogen-chemistry",
      summary: "",
      subtopics: [
        {
          title: "Nitrogen Molecule Structure",
          slug: "nitrogen-molecule-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Triple Bond (Nitrogen)",
          slug: "triple-bond-nitrogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nitrogen এর নিষ্ক্রিয়তা",
          slug: "nitrogen-er-nishkriyta",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Preparation of Nitrogen",
          slug: "preparation-of-nitrogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ammonia (NH₃)",
          slug: "ammonia-nh",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nitric Acid (HNO₃)",
          slug: "nitric-acid-hno",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nitrite",
          slug: "nitrite",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nitrate",
          slug: "nitrate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nitrogen Oxide",
          slug: "nitrogen-oxide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Atmospheric Nitrogen",
          slug: "atmospheric-nitrogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fixation",
          slug: "fixation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biological Importance (Nitrogen)",
          slug: "biological-importance-nitrogen",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Phosphorus Chemistry",
      slug: "phosphorus-chemistry",
      summary: "",
      subtopics: [
        {
          title: "Phosphorus এর Allotrope",
          slug: "phosphorus-er-allotrope",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "White Phosphorus",
          slug: "white-phosphorus",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Red Phosphorus",
          slug: "red-phosphorus",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Black Phosphorus",
          slug: "black-phosphorus",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Phosphine (PH₃)",
          slug: "phosphine-ph",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Phosphorus Halide",
          slug: "phosphorus-halide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Phosphoric Acid",
          slug: "phosphoric-acid",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Phosphate",
          slug: "phosphate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সার শিল্প (Phosphorus)",
          slug: "sar-shilp-phosphorus",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Match Industry",
          slug: "match-industry",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Biological System (Phosphorus)",
          slug: "biological-system-phosphorus",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter351;
