// lib/seedData/inorganic/3-53-silicon-silicate-chemistry.ts
//
// অধ্যায় 3.53 — Silicon ও Silicate Chemistry (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter353: SeedChapter = {
  code: "3.53",
  category: "inorganic-chemistry",
  chapterTitle: "Silicon ও Silicate Chemistry",
  chapterOrder: 530,
  topics: [
    {
      title: "Silicon Chemistry",
      slug: "silicon-chemistry",
      summary: "",
      subtopics: [
        {
          title: "Silicon এর অবস্থান",
          slug: "silicon-er-absthan",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Silicon Structure",
          slug: "silicon-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Catenation (Silicon)",
          slug: "catenation-silicon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Silane",
          slug: "silane",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "SiH₄ প্রস্তুতি",
          slug: "sih-prstuti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "SiH₄ ধর্ম",
          slug: "sih-dhrm",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Silicon Halide",
          slug: "silicon-halide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "SiCl₄",
          slug: "sicl",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Hydrolysis (Silicon)",
          slug: "hydrolysis-silicon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Silicon Oxide",
          slug: "silicon-oxide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "SiO₂ Structure",
          slug: "sio-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Quartz",
          slug: "quartz",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glass Formation",
          slug: "glass-formation",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Silicate Chemistry",
      slug: "silicate-chemistry",
      summary: "",
      subtopics: [
        {
          title: "Silicate Structure",
          slug: "silicate-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Orthosilicate",
          slug: "orthosilicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Pyrosilicate",
          slug: "pyrosilicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Chain Silicate",
          slug: "chain-silicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Sheet Silicate",
          slug: "sheet-silicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Cement Chemistry",
          slug: "cement-chemistry",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Clay Minerals",
          slug: "clay-minerals",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Zeolite (Silicate)",
          slug: "zeolite-silicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Construction Material",
          slug: "construction-material",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ceramic (Silicate)",
          slug: "ceramic-silicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Glass (Silicate)",
          slug: "glass-silicate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter353;
