// lib/seedData/inorganic/3-56-carbon-chemistry-inorganic.ts
//
// অধ্যায় 3.56 — Carbon Chemistry (অজৈব) (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter356: SeedChapter = {
  code: "3.56",
  category: "inorganic-chemistry",
  structure: "3-level",
  chapterTitle: "Carbon Chemistry (অজৈব)",
  chapterOrder: 560,
  topics: [
    {
      title: "কার্বনের মৌলিক ধারণা",
      slug: "karbner-moulik-dharna",
      summary: "",
      subtopics: [
        {
          title: "কার্বনের পর্যায় সারণিতে অবস্থান",
          slug: "karbner-pryay-sarnite-absthan",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electron Configuration (Carbon)",
          slug: "electron-configuration-carbon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Catenation ধর্ম (Carbon)",
          slug: "catenation-dhrm-carbon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Carbon এর অস্বাভাবিক বৈশিষ্ট্য",
          slug: "carbon-er-asbabhabik-boishishty",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Covalent Bond Formation (Carbon)",
          slug: "covalent-bond-formation-carbon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "Carbon এর Allotrope",
      slug: "carbon-er-allotrope",
      summary: "",
      subtopics: [
        {
          title: "Diamond",
          slug: "diamond",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Diamond Crystal Structure",
          slug: "diamond-crystal-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "sp³ Hybridization (Diamond)",
          slug: "sp-hybridization-diamond",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Diamond Hardness",
          slug: "diamond-hardness",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Diamond Thermal Conductivity",
          slug: "diamond-thermal-conductivity",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Graphite",
          slug: "graphite",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Graphite Layer Structure",
          slug: "graphite-layer-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "sp² Hybridization (Graphite)",
          slug: "sp-hybridization-graphite",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Graphite Electrical Conductivity",
          slug: "graphite-electrical-conductivity",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Fullerene (অজৈব কার্বন)",
          slug: "fullerene-ajoib-karbn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "C₆₀ Structure",
          slug: "c-structure",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Buckminster Fullerene",
          slug: "buckminster-fullerene",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular Cage",
          slug: "molecular-cage",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Graphene (অজৈব কার্বন)",
          slug: "graphene-ajoib-karbn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Single Carbon Layer",
          slug: "single-carbon-layer",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Electrical Property (Graphene)",
          slug: "electrical-property-graphene",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Mechanical Strength (Graphene)",
          slug: "mechanical-strength-graphene",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "কার্বনের অজৈব যৌগ",
      slug: "karbner-ajoib-youg",
      summary: "",
      subtopics: [
        {
          title: "Carbon Monoxide (CO)",
          slug: "carbon-monoxide-co",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Carbon Dioxide (CO₂, অজৈব)",
          slug: "carbon-dioxide-co-ajoib",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Carbonate Ion",
          slug: "carbonate-ion",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Bicarbonate Ion",
          slug: "bicarbonate-ion",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Metal Carbonate",
          slug: "metal-carbonate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ionic Carbide",
          slug: "ionic-carbide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Covalent Carbide",
          slug: "covalent-carbide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Interstitial Carbide",
          slug: "interstitial-carbide",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Metallurgy (Carbon)",
          slug: "metallurgy-carbon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Nanotechnology (Carbon)",
          slug: "nanotechnology-carbon",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter356;
