// lib/seedData/inorganic/3-6-p-block-elements.ts
//
// অধ্যায় 3.6 — p-ব্লক মৌল (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter36: SeedChapter = {
  code: "3.6",
  category: "inorganic-chemistry",
  chapterTitle: "p-ব্লক মৌল",
  chapterOrder: 60,
  topics: [
    {
      title: "p-ব্লক মৌল (গ্রুপ ১৩–১৪)",
      slug: "p-blk-moul-grup-1314",
      summary: "",
      subtopics: [
        {
          title: "p-ব্লকের পরিচয়",
          slug: "p-blker-prichy",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গ্রুপ-১৩",
          slug: "grup-13",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "বোরন",
          slug: "born",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অ্যালুমিনিয়াম",
          slug: "ayaluminiyam",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গ্রুপ-১৪",
          slug: "grup-14",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কার্বন (p-ব্লকে)",
          slug: "karbn-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সিলিকন",
          slug: "silikn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "টিন",
          slug: "tin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সীসা",
          slug: "siisa",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গুরুত্বপূর্ণ যৌগ (গ্রুপ ১৩-১৪)",
          slug: "gurutbpuurn-youg-grup-13-14",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "শিল্পে ব্যবহার (গ্রুপ ১৩-১৪)",
          slug: "shilpe-bybhar-grup-13-14",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "রাসায়নিক ধর্ম (গ্রুপ ১৩-১৪)",
          slug: "rasaynik-dhrm-grup-13-14",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "p-ব্লক মৌল (গ্রুপ ১৫–১৮)",
      slug: "p-blk-moul-grup-1518",
      summary: "",
      subtopics: [
        {
          title: "গ্রুপ-১৫",
          slug: "grup-15",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "নাইট্রোজেন (p-ব্লকে)",
          slug: "naitrojen-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ফসফরাস (p-ব্লকে)",
          slug: "phsphras-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আর্সেনিক",
          slug: "aarsenik",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গ্রুপ-১৬",
          slug: "grup-16",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অক্সিজেন (p-ব্লকে)",
          slug: "aksijen-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সালফার (p-ব্লকে)",
          slug: "salphar-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গ্রুপ-১৭",
          slug: "grup-17",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "হ্যালোজেন (p-ব্লকে)",
          slug: "hyalojen-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ক্লোরিন",
          slug: "klorin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ব্রোমিন",
          slug: "bromin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "আয়োডিন",
          slug: "aayodin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "গ্রুপ-১৮",
          slug: "grup-18",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "নিষ্ক্রিয় গ্যাস (p-ব্লকে)",
          slug: "nishkriy-gyas-p-blke",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ব্যবহার (গ্রুপ ১৫-১৮)",
          slug: "bybhar-grup-15-18",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "যৌগসমূহ (গ্রুপ ১৫-১৮)",
          slug: "yougsmuuh-grup-15-18",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter36;
