// lib/seedData/inorganic/3-9-coordination-chemistry.ts
//
// অধ্যায় 3.9 — সমন্বয় রসায়ন (Inorganic Chemistry)
// নোট: এই ফাইলের সাব-টপিকগুলো এখনো placeholder — শুধু title/slug বসানো হয়েছে।
// content (introduction, theory, applications, notes ইত্যাদি) পরে পূরণ করতে হবে।

import { SeedChapter } from "../types";

const chapter39: SeedChapter = {
  code: "3.9",
  category: "inorganic-chemistry",
  chapterTitle: "সমন্বয় রসায়ন",
  chapterOrder: 90,
  topics: [
    {
      title: "সমন্বয় যৌগের মৌলিক ধারণা",
      slug: "smnby-youger-moulik-dharna",
      summary: "",
      subtopics: [
        {
          title: "সমন্বয় যৌগের সংজ্ঞা",
          slug: "smnby-youger-sngjnya",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কেন্দ্রীয় ধাতু আয়ন",
          slug: "kendriiy-dhatu-aayn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "লিগ্যান্ড (Ligand)",
          slug: "ligyand-ligand",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "সমন্বয় সংখ্যা (Coordination Number)",
          slug: "smnby-sngkhya-coordination-number",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কো-অর্ডিনেশন গোলক",
          slug: "ko-ardineshn-golk",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কাউন্টার আয়ন",
          slug: "kauntar-aayn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "লিগ্যান্ডের শ্রেণিবিভাগ",
      slug: "ligyander-shrenibibhag",
      summary: "",
      subtopics: [
        {
          title: "একদন্ত লিগ্যান্ড (Monodentate)",
          slug: "ekdnt-ligyand-monodentate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "দ্বিদন্ত লিগ্যান্ড (Bidentate)",
          slug: "dbidnt-ligyand-bidentate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "বহুদন্ত লিগ্যান্ড (Polydentate)",
          slug: "bhudnt-ligyand-polydentate",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "কিলেট লিগ্যান্ড (Chelating Ligand)",
          slug: "kilet-ligyand-chelating-ligand",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "অ্যাম্বিডেন্টেট লিগ্যান্ড",
          slug: "ayambidentet-ligyand",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "সমন্বয় যৌগের নামকরণ",
      slug: "smnby-youger-namkrn",
      summary: "",
      subtopics: [
        {
          title: "IUPAC নামকরণের নিয়ম",
          slug: "iupac-namkrner-niym",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "লিগ্যান্ডের নামকরণ",
          slug: "ligyander-namkrn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ধাতুর নামকরণ",
          slug: "dhatur-namkrn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "জারণ অবস্থা নির্ণয়",
          slug: "jarn-abstha-nirny",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "সমন্বয় যৌগের গঠন",
      slug: "smnby-youger-gthn",
      summary: "",
      subtopics: [
        {
          title: "Werner এর তত্ত্ব",
          slug: "werner-er-tttb",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Valence Bond Theory (VBT)",
          slug: "valence-bond-theory-vbt",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Crystal Field Theory (CFT)",
          slug: "crystal-field-theory-cft",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Ligand Field Theory (LFT)",
          slug: "ligand-field-theory-lft",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Molecular Orbital Theory (MOT)",
          slug: "molecular-orbital-theory-mot",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "জ্যামিতিক গঠন",
      slug: "jyamitik-gthn",
      summary: "",
      subtopics: [
        {
          title: "Linear",
          slug: "linear",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Tetrahedral",
          slug: "tetrahedral",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Square planar",
          slug: "square-planar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Octahedral",
          slug: "octahedral",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Trigonal planar",
          slug: "trigonal-planar",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Trigonal bipyramidal",
          slug: "trigonal-bipyramidal",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "সমন্বয় যৌগের ধর্ম",
      slug: "smnby-youger-dhrm",
      summary: "",
      subtopics: [
        {
          title: "রঙের উৎপত্তি",
          slug: "rnger-utptti",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "চৌম্বক ধর্ম (সমন্বয় যৌগ)",
          slug: "choumbk-dhrm-smnby-youg",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "উচ্চ স্পিন ও নিম্ন স্পিন যৌগ",
          slug: "uchch-spin-o-nimn-spin-youg",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Isomerism (সমন্বয় যৌগ)",
          slug: "isomerism-smnby-youg",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Optical isomerism",
          slug: "optical-isomerism-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "Geometrical isomerism",
          slug: "geometrical-isomerism-2",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },

    {
      title: "গুরুত্বপূর্ণ সমন্বয় যৌগ",
      slug: "gurutbpuurn-smnby-youg",
      summary: "",
      subtopics: [
        {
          title: "[Cu(NH₃)₄]²⁺",
          slug: "cu-nh",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "[Fe(CN)₆]³⁻",
          slug: "fe-cn",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "[Co(NH₃)₆]³⁺",
          slug: "co-nh",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "হিমোগ্লোবিন",
          slug: "himoglobin",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ক্লোরোফিল",
          slug: "klorophil",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
        {
          title: "ভিটামিন B12",
          slug: "bhitamin-b12",
          estimatedTime: 15,
          level: "intermediate",
          summary: "",
          content: {
            introduction: "",
            theory: [],
            applications: [],
            notes: [],
          },
        },
      ],
    },
  ],
};

export default chapter39;
